#!/usr/bin/env python3
"""
Analyze Procrustes Effects - Statistical Analysis & Visualization

Generates comprehensive analysis of Procrustes alignment effects across all subjects.

Outputs:
  1. procrustes_effect_distributions.png (5-panel figure)
  2. procrustes_effect_by_roi.png (ROI comparison)
  3. procrustes_effect_hc_vs_cvd.png (Group comparison)
  4. baseline_performance_summary.json (Statistics)

Usage:
    python analyze_procrustes_effects.py

Author: Generated by Claude Code
Date: 2026-01-30
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import json
from scipy import stats

# Configuration
BASE_DIR = Path(__file__).parent / "results" / "baseline"
EVALUATION_FILE = BASE_DIR / "evaluation_all_subjects.json"

# Subject groups
HC_SUBJECTS = [f"{i:02d}" for i in range(1, 8)]   # sub-01 ~ sub-07
CVD_SUBJECTS = [f"{i:02d}" for i in range(8, 11)]  # sub-08 ~ sub-10

# Colors
sns.set_style('whitegrid')
sns.set_context('talk')


def load_data():
    """Load evaluation results as DataFrame"""

    if not EVALUATION_FILE.exists():
        raise FileNotFoundError(f"Evaluation file not found: {EVALUATION_FILE}\n"
                                "Run evaluate_baseline_all.py first!")

    with open(EVALUATION_FILE) as f:
        data = json.load(f)

    # Convert to DataFrame
    df = pd.DataFrame.from_dict(data, orient='index')

    # Add group label
    df['group'] = df['subject'].apply(
        lambda x: 'HC' if x in HC_SUBJECTS else 'CVD'
    )

    # Report NaN cases
    n_total = len(df)
    n_nan_rdm = df['rdm_correlation_after'].isna().sum()
    n_nan_decoding = df['decoding_accuracy_after'].isna().sum()

    if n_nan_rdm > 0:
        print(f"⚠️  {n_nan_rdm}/{n_total} cases with NaN RDM (will be excluded from RDM plots)")
        nan_cases = df[df['rdm_correlation_after'].isna()].index.tolist()
        for case in nan_cases:
            print(f"    - {case}")
        print()

    return df


def filter_paired_data(data_before, data_after):
    """
    Filter out NaN values from paired data for statistical tests

    Returns:
        valid_before, valid_after (arrays without NaN in either)
    """
    mask = ~(np.isnan(data_before) | np.isnan(data_after))
    return data_before[mask], data_after[mask]


def plot_before_after_distributions(df, output_dir):
    """
    Figure 1: 5-panel Procrustes effect distributions

    Panels:
      A: RDM Correlation (Before vs After)
      B: RDM Crossnobis (Before vs After)
      C: Decoding Accuracy (Before vs After)
      D: Improvement Distributions
      E: Procrustes Disparity Distribution
    """

    fig, axes = plt.subplots(2, 3, figsize=(20, 12))
    axes = axes.flatten()

    # Panel A: RDM Correlation
    ax = axes[0]
    data_before = df['rdm_correlation_before'].values
    data_after = df['rdm_correlation_after'].values

    # Filter valid data for plotting
    valid_before, valid_after = filter_paired_data(data_before, data_after)

    if len(valid_before) > 0:
        parts = ax.violinplot([valid_before, valid_after],
                              positions=[0, 1],
                              widths=0.7,
                              showmeans=True,
                              showextrema=True)

        # Color
        parts['bodies'][0].set_facecolor('coral')
        parts['bodies'][0].set_alpha(0.7)
        parts['bodies'][1].set_facecolor('skyblue')
        parts['bodies'][1].set_alpha(0.7)

        # Paired lines (only for valid data)
        for idx in df.index:
            before_val = df.loc[idx, 'rdm_correlation_before']
            after_val = df.loc[idx, 'rdm_correlation_after']
            if not (np.isnan(before_val) or np.isnan(after_val)):
                ax.plot([0, 1], [before_val, after_val],
                        'gray', alpha=0.2, linewidth=0.5)

    ax.set_xticks([0, 1])
    ax.set_xticklabels(['Before\nProcrustes', 'After\nProcrustes'])
    ax.set_ylabel('RDM Correlation Reliability')
    ax.set_title(f'A. RDM Correlation (n={len(valid_before)})')
    ax.axhline(0, color='black', linestyle='--', linewidth=1, alpha=0.5)

    # Wilcoxon test (only on valid pairs)
    if len(valid_before) > 0:
        stat, p = stats.wilcoxon(valid_before, valid_after, alternative='less')
        ax.text(0.5, ax.get_ylim()[1]*0.95, f'Wilcoxon p={p:.2e}',
                ha='center', fontsize=10, bbox=dict(boxstyle='round', facecolor='wheat'))

    # Panel B: RDM Crossnobis
    ax = axes[1]
    data_before = df['rdm_crossnobis_before'].values
    data_after = df['rdm_crossnobis_after'].values

    # Filter valid data
    valid_before, valid_after = filter_paired_data(data_before, data_after)

    if len(valid_before) > 0:
        parts = ax.violinplot([valid_before, valid_after],
                              positions=[0, 1],
                              widths=0.7,
                              showmeans=True,
                              showextrema=True)

        parts['bodies'][0].set_facecolor('coral')
        parts['bodies'][0].set_alpha(0.7)
        parts['bodies'][1].set_facecolor('skyblue')
        parts['bodies'][1].set_alpha(0.7)

        # Paired lines (only for valid data)
        for idx in df.index:
            before_val = df.loc[idx, 'rdm_crossnobis_before']
            after_val = df.loc[idx, 'rdm_crossnobis_after']
            if not (np.isnan(before_val) or np.isnan(after_val)):
                ax.plot([0, 1], [before_val, after_val],
                        'gray', alpha=0.2, linewidth=0.5)

    ax.set_xticks([0, 1])
    ax.set_xticklabels(['Before\nProcrustes', 'After\nProcrustes'])
    ax.set_ylabel('RDM Crossnobis Reliability')
    ax.set_title(f'B. RDM Crossnobis (n={len(valid_before)})')
    ax.axhline(0, color='black', linestyle='--', linewidth=1, alpha=0.5)

    if len(valid_before) > 0:
        stat, p = stats.wilcoxon(valid_before, valid_after, alternative='less')
        ax.text(0.5, ax.get_ylim()[1]*0.95, f'Wilcoxon p={p:.2e}',
                ha='center', fontsize=10, bbox=dict(boxstyle='round', facecolor='wheat'))

    # Panel C: Decoding Accuracy
    ax = axes[2]
    data_before = df['decoding_accuracy_before']
    data_after = df['decoding_accuracy_after']

    parts = ax.violinplot([data_before, data_after],
                          positions=[0, 1],
                          widths=0.7,
                          showmeans=True,
                          showextrema=True)

    parts['bodies'][0].set_facecolor('coral')
    parts['bodies'][0].set_alpha(0.7)
    parts['bodies'][1].set_facecolor('skyblue')
    parts['bodies'][1].set_alpha(0.7)

    for idx in df.index:
        ax.plot([0, 1],
                [df.loc[idx, 'decoding_accuracy_before'],
                 df.loc[idx, 'decoding_accuracy_after']],
                'gray', alpha=0.2, linewidth=0.5)

    ax.set_xticks([0, 1])
    ax.set_xticklabels(['Before\nProcrustes', 'After\nProcrustes'])
    ax.set_ylabel('Decoding Accuracy')
    ax.set_title('C. Decoding Accuracy (LORO, 8-class)')
    ax.axhline(0.125, color='red', linestyle='--', linewidth=1, alpha=0.5, label='Chance (12.5%)')
    ax.legend(loc='lower right', fontsize=10)

    stat, p = stats.wilcoxon(data_before, data_after, alternative='less')
    ax.text(0.5, ax.get_ylim()[1]*0.95, f'Wilcoxon p={p:.2e}',
            ha='center', fontsize=10, bbox=dict(boxstyle='round', facecolor='wheat'))

    # Panel D: Improvement Distributions
    ax = axes[3]
    improvements = [
        ('RDM Corr', df['rdm_correlation_improvement'].dropna()),
        ('RDM Xnobis', df['rdm_crossnobis_improvement'].dropna()),
        ('Decoding', df['decoding_improvement'].dropna())
    ]

    colors = ['steelblue', 'seagreen', 'mediumpurple']

    for i, (label, data) in enumerate(improvements):
        if len(data) > 0:
            ax.hist(data, bins=15, alpha=0.6, color=colors[i], label=label, edgecolor='black')

    ax.axvline(0, color='black', linestyle='--', linewidth=2, label='No improvement')
    ax.set_xlabel('Improvement (After - Before)')
    ax.set_ylabel('Count')
    ax.set_title('D. Improvement Distributions')
    ax.legend(loc='upper right', fontsize=10)

    # Annotate % positive
    for label, data in improvements:
        if len(data) > 0:
            pct_positive = 100 * np.sum(data > 0) / len(data)
            mean_imp = np.mean(data)
            ax.text(0.02, 0.98 - improvements.index((label, data))*0.08,
                    f'{label}: {pct_positive:.1f}% positive (n={len(data)}, mean: {mean_imp:+.3f})',
                    transform=ax.transAxes, fontsize=9,
                    verticalalignment='top',
                    bbox=dict(boxstyle='round', facecolor=colors[improvements.index((label, data))], alpha=0.3))

    # Panel E: Procrustes Disparity
    ax = axes[4]
    disparities = df['procrustes_disparity'].dropna()

    ax.hist(disparities, bins=20, color='orange', alpha=0.7, edgecolor='black')
    ax.axvline(np.median(disparities), color='red', linestyle='--', linewidth=2,
               label=f'Median: {np.median(disparities):.1f}')
    ax.set_xlabel('Procrustes Disparity')
    ax.set_ylabel('Count')
    ax.set_title('E. Procrustes Disparity Distribution')
    ax.legend(loc='upper right')

    # Annotate statistics
    ax.text(0.98, 0.98,
            f'Mean: {np.mean(disparities):.1f}\n'
            f'Range: [{np.min(disparities):.1f}, {np.max(disparities):.1f}]',
            transform=ax.transAxes, fontsize=10,
            verticalalignment='top', horizontalalignment='right',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))

    # Remove unused axis
    fig.delaxes(axes[5])

    plt.tight_layout()

    output_file = output_dir / 'procrustes_effect_distributions.png'
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"✓ Saved: {output_file}")

    plt.close()


def plot_roi_comparison(df, output_dir):
    """
    Figure 2: ROI Comparison

    Boxplots: RDM reliability (before/after) per ROI
    """

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    # Panel A: Before Procrustes
    ax = axes[0]
    data_before = df.pivot_table(values='rdm_correlation_before', index=df.index, columns='roi')
    data_before = data_before[['V1', 'V2', 'V3', 'hV4']]  # Order

    bp = ax.boxplot([data_before[roi].dropna() for roi in ['V1', 'V2', 'V3', 'hV4']],
                     labels=['V1', 'V2', 'V3', 'hV4'],
                     patch_artist=True)

    for patch in bp['boxes']:
        patch.set_facecolor('coral')
        patch.set_alpha(0.7)

    ax.set_ylabel('RDM Correlation Reliability')
    ax.set_title('Before Procrustes')
    ax.axhline(0, color='black', linestyle='--', linewidth=1, alpha=0.5)
    ax.grid(axis='y', alpha=0.3)

    # Panel B: After Procrustes
    ax = axes[1]
    data_after = df.pivot_table(values='rdm_correlation_after', index=df.index, columns='roi')
    data_after = data_after[['V1', 'V2', 'V3', 'hV4']]

    bp = ax.boxplot([data_after[roi].dropna() for roi in ['V1', 'V2', 'V3', 'hV4']],
                     labels=['V1', 'V2', 'V3', 'hV4'],
                     patch_artist=True)

    for patch in bp['boxes']:
        patch.set_facecolor('skyblue')
        patch.set_alpha(0.7)

    ax.set_ylabel('RDM Correlation Reliability')
    ax.set_title('After Procrustes')
    ax.axhline(0, color='black', linestyle='--', linewidth=1, alpha=0.5)
    ax.grid(axis='y', alpha=0.3)

    # ANOVA test
    from scipy.stats import f_oneway
    roi_data = [data_after[roi].dropna() for roi in ['V1', 'V2', 'V3', 'hV4']]
    f_stat, p_anova = f_oneway(*roi_data)

    ax.text(0.5, 0.02, f'ANOVA: F={f_stat:.2f}, p={p_anova:.3f}',
            transform=ax.transAxes, ha='center',
            bbox=dict(boxstyle='round', facecolor='wheat'))

    plt.tight_layout()

    output_file = output_dir / 'procrustes_effect_by_roi.png'
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"✓ Saved: {output_file}")

    plt.close()


def plot_hc_vs_cvd(df, output_dir):
    """
    Figure 3: HC vs CVD Comparison

    3-panel comparison across groups
    """

    fig, axes = plt.subplots(1, 3, figsize=(18, 6))

    # Panel A: RDM Reliability (after Procrustes)
    ax = axes[0]
    hc_data = df[df['group'] == 'HC']['rdm_correlation_after'].dropna()
    cvd_data = df[df['group'] == 'CVD']['rdm_correlation_after'].dropna()

    bp = ax.boxplot([hc_data, cvd_data],
                     labels=[f'HC (n={len(hc_data)})', f'CVD (n={len(cvd_data)})'],
                     patch_artist=True)

    bp['boxes'][0].set_facecolor('lightblue')
    bp['boxes'][1].set_facecolor('lightcoral')

    ax.set_ylabel('RDM Correlation Reliability\n(after Procrustes)')
    ax.set_title('A. RDM Reliability by Group')
    ax.grid(axis='y', alpha=0.3)

    # Mann-Whitney U test
    if len(hc_data) > 0 and len(cvd_data) > 0:
        u_stat, p = stats.mannwhitneyu(hc_data, cvd_data, alternative='two-sided')
        ax.text(0.5, 0.98, f'Mann-Whitney U: p={p:.3f}',
                transform=ax.transAxes, ha='center', va='top',
                bbox=dict(boxstyle='round', facecolor='wheat'))

    # Panel B: Decoding Accuracy (after Procrustes)
    ax = axes[1]
    hc_data = df[df['group'] == 'HC']['decoding_accuracy_after']
    cvd_data = df[df['group'] == 'CVD']['decoding_accuracy_after']

    bp = ax.boxplot([hc_data, cvd_data],
                     labels=['HC (n=28)', 'CVD (n=12)'],
                     patch_artist=True)

    bp['boxes'][0].set_facecolor('lightblue')
    bp['boxes'][1].set_facecolor('lightcoral')

    ax.set_ylabel('Decoding Accuracy\n(after Procrustes)')
    ax.set_title('B. Decoding Accuracy by Group')
    ax.axhline(0.125, color='red', linestyle='--', linewidth=1, alpha=0.5, label='Chance')
    ax.legend(loc='lower right')
    ax.grid(axis='y', alpha=0.3)

    u_stat, p = stats.mannwhitneyu(hc_data, cvd_data, alternative='two-sided')
    ax.text(0.5, 0.98, f'Mann-Whitney U: p={p:.3f}',
            transform=ax.transAxes, ha='center', va='top',
            bbox=dict(boxstyle='round', facecolor='wheat'))

    # Panel C: Procrustes Disparity
    ax = axes[2]
    hc_data = df[df['group'] == 'HC']['procrustes_disparity'].dropna()
    cvd_data = df[df['group'] == 'CVD']['procrustes_disparity'].dropna()

    bp = ax.boxplot([hc_data, cvd_data],
                     labels=['HC (n=28)', 'CVD (n=12)'],
                     patch_artist=True)

    bp['boxes'][0].set_facecolor('lightblue')
    bp['boxes'][1].set_facecolor('lightcoral')

    ax.set_ylabel('Procrustes Disparity')
    ax.set_title('C. Alignment Quality by Group')
    ax.grid(axis='y', alpha=0.3)

    u_stat, p = stats.mannwhitneyu(hc_data, cvd_data, alternative='two-sided')
    ax.text(0.5, 0.98, f'Mann-Whitney U: p={p:.3f}',
            transform=ax.transAxes, ha='center', va='top',
            bbox=dict(boxstyle='round', facecolor='wheat'))

    plt.tight_layout()

    output_file = output_dir / 'procrustes_effect_hc_vs_cvd.png'
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"✓ Saved: {output_file}")

    plt.close()


def compute_summary_statistics(df, output_dir):
    """Compute and save summary statistics"""

    # Count valid (non-NaN) measurements
    n_valid_rdm = df['rdm_correlation_after'].notna().sum()
    n_valid_rdm_improvement = df['rdm_correlation_improvement'].notna().sum()
    n_valid_decoding = df['decoding_accuracy_after'].notna().sum()

    summary = {
        'overall': {
            'n_total': len(df),
            'n_valid_rdm': int(n_valid_rdm),
            'n_valid_decoding': int(n_valid_decoding),
            'rdm_correlation_before': {
                'mean': float(df['rdm_correlation_before'].mean()),
                'std': float(df['rdm_correlation_before'].std()),
                'median': float(df['rdm_correlation_before'].median()),
                'range': [float(df['rdm_correlation_before'].min()),
                         float(df['rdm_correlation_before'].max())]
            },
            'rdm_correlation_after': {
                'mean': float(df['rdm_correlation_after'].mean()),
                'std': float(df['rdm_correlation_after'].std()),
                'median': float(df['rdm_correlation_after'].median()),
                'range': [float(df['rdm_correlation_after'].min()),
                         float(df['rdm_correlation_after'].max())]
            },
            'rdm_correlation_improvement': {
                'mean': float(df['rdm_correlation_improvement'].mean()),
                'std': float(df['rdm_correlation_improvement'].std()),
                'percent_positive': float(100 * (df['rdm_correlation_improvement'] > 0).sum() / n_valid_rdm_improvement) if n_valid_rdm_improvement > 0 else 0.0
            },
            'decoding_accuracy_before': {
                'mean': float(df['decoding_accuracy_before'].mean()),
                'std': float(df['decoding_accuracy_before'].std())
            },
            'decoding_accuracy_after': {
                'mean': float(df['decoding_accuracy_after'].mean()),
                'std': float(df['decoding_accuracy_after'].std())
            },
            'decoding_improvement': {
                'mean': float(df['decoding_improvement'].mean()),
                'std': float(df['decoding_improvement'].std()),
                'percent_positive': float(100 * (df['decoding_improvement'] > 0).sum() / n_valid_decoding) if n_valid_decoding > 0 else 0.0
            },
            'procrustes_disparity': {
                'mean': float(df['procrustes_disparity'].mean()),
                'median': float(df['procrustes_disparity'].median()),
                'range': [float(df['procrustes_disparity'].min()),
                         float(df['procrustes_disparity'].max())]
            }
        },
        'by_group': {}
    }

    # Group statistics
    for group in ['HC', 'CVD']:
        group_df = df[df['group'] == group]
        summary['by_group'][group] = {
            'n': len(group_df),
            'rdm_correlation_after': {
                'mean': float(group_df['rdm_correlation_after'].mean()),
                'std': float(group_df['rdm_correlation_after'].std())
            },
            'decoding_accuracy_after': {
                'mean': float(group_df['decoding_accuracy_after'].mean()),
                'std': float(group_df['decoding_accuracy_after'].std())
            }
        }

    # Save
    output_file = output_dir / 'baseline_performance_summary.json'
    with open(output_file, 'w') as f:
        json.dump(summary, f, indent=2)

    print(f"✓ Saved: {output_file}")

    return summary


def main():
    """Main analysis pipeline"""

    print("="*80)
    print("Procrustes Effect Analysis")
    print("="*80)

    # Load data
    print("\nLoading evaluation results...")
    df = load_data()
    print(f"✓ Loaded {len(df)} subject-ROI pairs")

    # Check groups
    n_hc = (df['group'] == 'HC').sum()
    n_cvd = (df['group'] == 'CVD').sum()
    print(f"  HC:  {n_hc} pairs (7 subjects × 4 ROIs)")
    print(f"  CVD: {n_cvd} pairs (3 subjects × 4 ROIs)")

    # Generate figures
    print("\nGenerating visualizations...")

    print("  Figure 1: Procrustes effect distributions (5-panel)...")
    plot_before_after_distributions(df, BASE_DIR)

    print("  Figure 2: ROI comparison...")
    plot_roi_comparison(df, BASE_DIR)

    print("  Figure 3: HC vs CVD comparison...")
    plot_hc_vs_cvd(df, BASE_DIR)

    # Summary statistics
    print("\nComputing summary statistics...")
    summary = compute_summary_statistics(df, BASE_DIR)

    # Print key findings
    print("\n" + "="*80)
    print("Key Findings")
    print("="*80)

    print("\nOverall Performance (n={})".format(len(df)))
    print("  RDM Correlation:")
    print(f"    Before:      {summary['overall']['rdm_correlation_before']['mean']:.3f} ± "
          f"{summary['overall']['rdm_correlation_before']['std']:.3f}")
    print(f"    After:       {summary['overall']['rdm_correlation_after']['mean']:.3f} ± "
          f"{summary['overall']['rdm_correlation_after']['std']:.3f}")
    print(f"    Improvement: {summary['overall']['rdm_correlation_improvement']['mean']:+.3f} ± "
          f"{summary['overall']['rdm_correlation_improvement']['std']:.3f} "
          f"({summary['overall']['rdm_correlation_improvement']['percent_positive']:.1f}% positive)")

    print("  Decoding Accuracy:")
    print(f"    Before:      {summary['overall']['decoding_accuracy_before']['mean']:.3f} ± "
          f"{summary['overall']['decoding_accuracy_before']['std']:.3f}")
    print(f"    After:       {summary['overall']['decoding_accuracy_after']['mean']:.3f} ± "
          f"{summary['overall']['decoding_accuracy_after']['std']:.3f}")
    print(f"    Improvement: {summary['overall']['decoding_improvement']['mean']:+.3f} ± "
          f"{summary['overall']['decoding_improvement']['std']:.3f} "
          f"({summary['overall']['decoding_improvement']['percent_positive']:.1f}% positive)")

    print("\nGroup Comparison:")
    for group in ['HC', 'CVD']:
        stats = summary['by_group'][group]
        print(f"  {group} (n={stats['n']}):")
        print(f"    RDM (after):     {stats['rdm_correlation_after']['mean']:.3f} ± "
              f"{stats['rdm_correlation_after']['std']:.3f}")
        print(f"    Decoding (after): {stats['decoding_accuracy_after']['mean']:.3f} ± "
              f"{stats['decoding_accuracy_after']['std']:.3f}")

    print("\n" + "="*80)
    print("✅ Analysis complete!")
    print("")
    print("Generated files:")
    print(f"  - {BASE_DIR}/procrustes_effect_distributions.png")
    print(f"  - {BASE_DIR}/procrustes_effect_by_roi.png")
    print(f"  - {BASE_DIR}/procrustes_effect_hc_vs_cvd.png")
    print(f"  - {BASE_DIR}/baseline_performance_summary.json")
    print("="*80)


if __name__ == "__main__":
    main()
