#!/usr/bin/env python3
"""
Comprehensive Evaluation of Baseline Pipeline

Computes metrics before and after Procrustes alignment for all subject-ROI pairs.

Metrics:
  1. RDM correlation reliability (Pearson-based)
  2. RDM crossnobis reliability (Mahalanobis with Ledoit-Wolf)
  3. Decoding accuracy (leave-one-run-out)
  4. Procrustes disparity
  5. Improvements (delta metrics)

Usage:
    python evaluate_baseline_all.py

Inputs:
    results/baseline/sub-{ID}/{ROI}/amplitudes_raw.npy
    results/baseline/sub-{ID}/{ROI}/amplitudes_procrustes.npy

Outputs:
    results/baseline/evaluation_all_subjects.json

Author: Generated by Claude Code
Date: 2026-01-30
"""

import numpy as np
from pathlib import Path
import json
import sys
from scipy.stats import spearmanr

# Add utils to path
sys.path.insert(0, str(Path(__file__).parent / 'utils'))
from crossnobis_ldw import compute_crossnobis_rdms_per_run

# Configuration
SUBJECTS = [f"{i:02d}" for i in range(1, 11)]
ROIS = ['V1', 'V2', 'V3', 'hV4']
BASE_DIR = Path(__file__).parent / "results" / "baseline"


def compute_rdm_correlation_per_run(amplitudes):
    """
    Compute RDM per run using Pearson correlation

    Args:
        amplitudes: (n_runs, n_colors, n_voxels)

    Returns:
        rdms: (n_runs, n_colors, n_colors) - RDM per run
    """
    n_runs, n_colors, n_voxels = amplitudes.shape

    rdms = np.zeros((n_runs, n_colors, n_colors))

    for r in range(n_runs):
        patterns = amplitudes[r]  # (n_colors, n_voxels)
        corr_matrix = np.corrcoef(patterns)
        rdm = 1 - corr_matrix
        rdms[r] = rdm

    return rdms


def rdm_reliability_spearman(rdms):
    """
    Compute RDM reliability as mean Spearman correlation across run pairs

    Args:
        rdms: (n_runs, n_colors, n_colors)

    Returns:
        reliability: float - Mean pairwise correlation
    """
    n_runs, n_colors, _ = rdms.shape

    # Upper triangle indices
    triu_idx = np.triu_indices(n_colors, k=1)

    # Pairwise correlations
    correlations = []
    for i in range(n_runs):
        for j in range(i+1, n_runs):
            vec_i = rdms[i][triu_idx]
            vec_j = rdms[j][triu_idx]

            r, _ = spearmanr(vec_i, vec_j)
            correlations.append(r)

    return np.mean(correlations)


def decode_loro(amplitudes):
    """
    Leave-one-run-out decoding

    Args:
        amplitudes: (n_runs, n_colors, n_voxels)

    Returns:
        accuracy: float - Classification accuracy
    """
    n_runs, n_colors, n_voxels = amplitudes.shape

    correct = 0
    total = 0

    for test_run in range(n_runs):
        # Training runs
        train_runs = [r for r in range(n_runs) if r != test_run]
        train_mean = amplitudes[train_runs].mean(axis=0)  # (n_colors, n_voxels)

        # Test patterns
        test_patterns = amplitudes[test_run]

        # Classify each color
        for true_color in range(n_colors):
            test_pattern = test_patterns[true_color]

            # Compute distances to all training templates
            distances = np.linalg.norm(train_mean - test_pattern, axis=1)

            # Predict
            predicted_color = np.argmin(distances)

            if predicted_color == true_color:
                correct += 1
            total += 1

    accuracy = correct / total
    return accuracy


def evaluate_single_roi(subject, roi, verbose=True):
    """
    Evaluate single subject-ROI pair

    Returns:
        dict or None: Metrics if successful, None if failed
    """
    result_dir = BASE_DIR / f"sub-{subject}" / roi

    # Check files exist
    raw_path = result_dir / "amplitudes_raw.npy"
    procrustes_path = result_dir / "amplitudes_procrustes.npy"
    disparity_path = result_dir / "procrustes_disparities.npy"

    if not raw_path.exists():
        if verbose:
            print(f"⚠️  Skip: sub-{subject}/{roi} (amplitudes_raw.npy missing)")
        return None

    if not procrustes_path.exists():
        if verbose:
            print(f"⚠️  Skip: sub-{subject}/{roi} (amplitudes_procrustes.npy missing)")
        return None

    try:
        # Load data
        amplitudes_raw = np.load(raw_path)
        amplitudes_aligned = np.load(procrustes_path)

        n_runs, n_colors, n_voxels = amplitudes_raw.shape

        # === BEFORE Procrustes ===
        rdms_corr_before = compute_rdm_correlation_per_run(amplitudes_raw)
        rdm_corr_reliability_before = rdm_reliability_spearman(rdms_corr_before)

        rdms_crossnobis_before, shrinkages = compute_crossnobis_rdms_per_run(amplitudes_raw)
        rdm_crossnobis_reliability_before = rdm_reliability_spearman(rdms_crossnobis_before)

        decoding_accuracy_before = decode_loro(amplitudes_raw)

        # === Procrustes Disparity ===
        if disparity_path.exists():
            disparities = np.load(disparity_path)
            mean_disparity = float(np.mean(disparities))
        else:
            mean_disparity = np.nan

        # === AFTER Procrustes ===
        rdms_corr_after = compute_rdm_correlation_per_run(amplitudes_aligned)
        rdm_corr_reliability_after = rdm_reliability_spearman(rdms_corr_after)

        rdms_crossnobis_after, _ = compute_crossnobis_rdms_per_run(amplitudes_aligned)
        rdm_crossnobis_reliability_after = rdm_reliability_spearman(rdms_crossnobis_after)

        decoding_accuracy_after = decode_loro(amplitudes_aligned)

        # === Improvements ===
        rdm_corr_improvement = rdm_corr_reliability_after - rdm_corr_reliability_before
        rdm_crossnobis_improvement = rdm_crossnobis_reliability_after - rdm_crossnobis_reliability_before
        decoding_improvement = decoding_accuracy_after - decoding_accuracy_before

        # Compile results
        results = {
            # Metadata
            'subject': subject,
            'roi': roi,
            'n_voxels': int(n_voxels),

            # Before Procrustes
            'rdm_correlation_before': float(rdm_corr_reliability_before),
            'rdm_crossnobis_before': float(rdm_crossnobis_reliability_before),
            'decoding_accuracy_before': float(decoding_accuracy_before),

            # Procrustes
            'procrustes_disparity': float(mean_disparity),
            'shrinkage': float(np.mean(shrinkages)),

            # After Procrustes
            'rdm_correlation_after': float(rdm_corr_reliability_after),
            'rdm_crossnobis_after': float(rdm_crossnobis_reliability_after),
            'decoding_accuracy_after': float(decoding_accuracy_after),

            # Improvements
            'rdm_correlation_improvement': float(rdm_corr_improvement),
            'rdm_crossnobis_improvement': float(rdm_crossnobis_improvement),
            'decoding_improvement': float(decoding_improvement)
        }

        if verbose:
            print(f"✓ sub-{subject}/{roi}: "
                  f"RDM {rdm_corr_reliability_before:.3f}→{rdm_corr_reliability_after:.3f} "
                  f"({rdm_corr_improvement:+.3f}), "
                  f"Acc {decoding_accuracy_before:.3f}→{decoding_accuracy_after:.3f} "
                  f"({decoding_improvement:+.3f})")

        return results

    except Exception as e:
        print(f"❌ sub-{subject}/{roi}: {e}")
        return None


def main():
    """Evaluate all subject-ROI pairs"""

    print("="*80)
    print("Baseline Evaluation - All Subjects")
    print("="*80)
    print(f"Subjects: {len(SUBJECTS)} (sub-01 ~ sub-10)")
    print(f"ROIs: {len(ROIS)} (V1, V2, V3, hV4)")
    print(f"Total: {len(SUBJECTS) * len(ROIS)} pairs")
    print("")

    all_results = {}
    n_success = 0

    for subject in SUBJECTS:
        for roi in ROIS:
            key = f"sub-{subject}_{roi}"
            result = evaluate_single_roi(subject, roi, verbose=True)

            if result is not None:
                all_results[key] = result
                n_success += 1

    print("")
    print("="*80)
    print("Summary")
    print("="*80)
    print(f"✅ Evaluated: {n_success}/{len(SUBJECTS) * len(ROIS)}")

    if n_success > 0:
        # Summary statistics (arrays for analysis)
        rdm_before = np.array([r['rdm_correlation_before'] for r in all_results.values()])
        rdm_after = np.array([r['rdm_correlation_after'] for r in all_results.values()])
        rdm_improvement = np.array([r['rdm_correlation_improvement'] for r in all_results.values()])

        decoding_before = np.array([r['decoding_accuracy_before'] for r in all_results.values()])
        decoding_after = np.array([r['decoding_accuracy_after'] for r in all_results.values()])
        decoding_improvement = np.array([r['decoding_improvement'] for r in all_results.values()])

        # Count valid measurements (non-NaN)
        n_valid_rdm = np.sum(~np.isnan(rdm_after))
        n_valid_decoding = np.sum(~np.isnan(decoding_after))

        print("")
        print("Overall Performance:")
        print(f"  RDM Reliability (n_valid={n_valid_rdm}/{n_success}):")
        print(f"    Before:      {np.nanmean(rdm_before):.3f} ± {np.nanstd(rdm_before):.3f}")
        print(f"    After:       {np.nanmean(rdm_after):.3f} ± {np.nanstd(rdm_after):.3f}")
        print(f"    Improvement: {np.nanmean(rdm_improvement):+.3f} ± {np.nanstd(rdm_improvement):.3f}")
        print(f"    % Positive:  {100*np.nansum(rdm_improvement > 0)/n_valid_rdm:.1f}%")

        print(f"  Decoding Accuracy (n_valid={n_valid_decoding}/{n_success}):")
        print(f"    Before:      {np.nanmean(decoding_before):.3f} ± {np.nanstd(decoding_before):.3f}")
        print(f"    After:       {np.nanmean(decoding_after):.3f} ± {np.nanstd(decoding_after):.3f}")
        print(f"    Improvement: {np.nanmean(decoding_improvement):+.3f} ± {np.nanstd(decoding_improvement):.3f}")
        print(f"    % Positive:  {100*np.nansum(decoding_improvement > 0)/n_valid_decoding:.1f}%")

        # Report problematic cases
        nan_cases = [key for key, r in all_results.items() if np.isnan(r['rdm_correlation_after'])]
        if nan_cases:
            print("")
            print(f"⚠️  {len(nan_cases)} cases with NaN RDM (constant voxel patterns):")
            for case in nan_cases:
                print(f"    - {case}")

        # Save results
        output_file = BASE_DIR / "evaluation_all_subjects.json"
        with open(output_file, 'w') as f:
            json.dump(all_results, f, indent=2)

        print("")
        print(f"✅ Saved: {output_file}")

        print("")
        print("Next step:")
        print("  python analyze_procrustes_effects.py")

    print("="*80)


if __name__ == "__main__":
    main()
