"""S7 Nested LOO — robustness check on top of single-LOO S7 sprint.

The single-LOO S7 (`s7_loss_combo_subset.py`) selects and evaluates inside the
same 7-HC pool (subset resample → train/test split), so selection and evaluation
share the HC pool. This script adds an OUTER 7-fold LOO over HC and resamples
inner subsets only from the remaining 6 HC, so the outer-held-out HC is unseen
by parameter selection.

Per cell (subject × ROI):

  Outer loop: HC_i ∈ HC_SUBJS (7 folds)
    inner_pool = HC \\ {HC_i}              (size 6)
    inner_subsets = C(6, 4) = 15 subsets
    For each inner subset, fit:
      - models: R+C (3 Δλ sources for family) + 2-comp
      - losses: L_gamma, L_RDM
      - λ ∈ {0, 0.25, 0.5, 0.75, 1.0} on probe gamma_plus_RDM
    Inner CoV = parameter SD / |median| across 15 subsets.
    Median(δθ) → evaluate test L_γ on HC_i (held-out) using inner_pool as
    HC reference (Crawford-Howell-like specificity check: should be HIGH if
    fitted δθ captures real CVD axis).

  Aggregate per cell × (model × λ):
    - mean inner CoV across 7 outer folds
    - mean test L_γ across 7 outer folds
    - boundary-hit rate

Output: results/s7_nested_loo/cell_{idx:02d}_{subject}_{roi}.json
        (aggregated.json generated by post-processing script.)

CRITICAL: This is a *robustness check*. Real evaluation = Phase 3 behavioral
filter test. PI feedback (specificity / double-dipping) is only PARTIALLY
addressed: inner CoV is on a clean 6-HC pool, but the data is the same
fMRI dataset throughout.
"""

import argparse
import itertools
import json
import sys
import time
from pathlib import Path

import numpy as np

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from rc_1dof import g_grid, forward_rc
from two_comp import BS_GRID, BC_GRID, forward_2comp
from neural_loss import (
    load_amplitudes, load_hc_pool, ROI_K,
    precompute_loco_W_within,
)
from diagnostic_delta_rdm import precompute_hc_W
from behav_loss import (
    load_jnd_per_pair, load_8afc_per_color,
    HC_JND_SUBJS,
)
from utils_forward_model import create_basis_full, HUE_ANGLES

from s8_loo_train_test import (
    jnd_baseline_from_pool, make_loss_fns,
    HC_SUBJS, DELTA_LAMBDA_BY_FAMILY,
)

# Reuse helpers from the single-LOO S7 (do not modify that file).
from s7_loss_combo_subset import (
    zscore_grid,
    grid_eval_rc, grid_eval_2comp,
    argmin_rc_grid, argmin_2comp_grid,
    compute_train_grids,
    build_test_loss_fns,
    evaluate_loss_at_fit,
    fit_lambda_probe,
    fit_single_losses,
)

OUT_DIR = SCRIPT_DIR.parent / "results" / "s7_nested_loo"
ROIS = ['V1', 'V2', 'V3', 'V4']
ALL_SUBJECTS = [
    ('sub-08', 'deutan'),
    ('sub-09', 'protan'),
    ('sub-10', 'deutan'),  # near-normal null control (JND/8AFC missing → mostly None)
]

# Nested-LOO design (smaller than single-LOO S7 — only what's needed for
# the lambda-probe robustness statement).
INNER_K = 4               # subset size inside inner pool of 6
LAMBDA_VALUES = [0.0, 0.25, 0.5, 0.75, 1.0]
# Probe: gamma_plus_RDM (consistent with s7_lambda_optimal.py)
PROBE_BEHAV = ('L_gamma',)
PROBE_NEURAL = ('L_RDM',)
PROBE_COMPONENTS = list(PROBE_BEHAV) + list(PROBE_NEURAL)

CELLS = [(s, f, r) for (s, f) in ALL_SUBJECTS for r in ROIS]

# Names that the aggregator iterates over.
RC_VARIANTS = {
    'deutan': ['DPS_lit', 'Boehm_mid', 'JND_Lamb'],
    'protan': ['DPS_lit', 'Boehm_low', 'JND_Lamb'],
}


def extract_rc_param(fit_dict, src):
    """Extract g_best, loss_best, boundary flag from a fit_lambda_probe result."""
    if fit_dict is None:
        return None
    rc = fit_dict.get('rc', {}).get(src)
    if rc is None:
        return None
    return {
        'g_best': rc.get('g_best'),
        'loss_best': rc.get('loss_best'),
        'boundary': bool(rc.get('boundary_low') or rc.get('boundary_high')),
        'src': src,
    }


def extract_2comp_param(fit_dict):
    if fit_dict is None:
        return None
    twc = fit_dict.get('2comp')
    if twc is None:
        return None
    return {
        'beta_s_best': twc.get('beta_s_best'),
        'beta_c_best': twc.get('beta_c_best'),
        'loss_best': twc.get('loss_best'),
        'norm': twc.get('norm'),
        'boundary': bool(twc.get('boundary_bs') or twc.get('boundary_bc')),
    }


def cov_and_summary(values):
    """Median, SD (ddof=1), CoV; values may contain Nones / non-finite."""
    arr = np.array([v for v in values if v is not None and np.isfinite(v)], dtype=float)
    if arr.size == 0:
        return {'median': None, 'sd': None, 'cov': None, 'n_valid': 0}
    if arr.size == 1:
        return {
            'median': float(arr[0]),
            'sd': 0.0,
            'cov': 0.0 if abs(arr[0]) < 1e-10 else 0.0,
            'n_valid': 1,
        }
    med = float(np.median(arr))
    sd = float(np.std(arr, ddof=1))
    cov = (sd / abs(med)) if abs(med) > 1e-10 else None
    return {'median': med, 'sd': sd, 'cov': cov, 'n_valid': int(arr.size)}


def safe_mean(values):
    arr = np.array([v for v in values if v is not None and np.isfinite(v)], dtype=float)
    if arr.size == 0:
        return None
    return float(np.mean(arr))


def process_inner_for_outer(
    subject_data, cvd_amp_for_test_dummy,
    inner_pool, family, dl_sources, C_baseline, K, hc_amps_all,
):
    """For a single outer fold, run all 15 inner subsets and return:
       inner_results: list of per-subset fits across (model variant, λ).
    """
    inner_subsets = list(itertools.combinations(inner_pool, INNER_K))
    rc_srcs = list(dl_sources.keys())

    per_subset = []
    for subset in inner_subsets:
        subset_list = list(subset)
        grids, _ = compute_train_grids(
            subject_data, subset_list, family, dl_sources,
            C_baseline, K, hc_amps_all,
        )
        # Fit at each λ for the gamma+RDM probe.
        # grids dict structure: {loss_name: {'rc': {src: arr}, '2comp': arr}} or None
        per_lambda_fits = {}
        pure_rdm_fit = None
        gamma_available = (grids is not None and grids.get('L_gamma') is not None)
        rdm_available = (grids is not None and grids.get('L_RDM') is not None)

        for lam in LAMBDA_VALUES:
            if grids is None:
                per_lambda_fits[f"{lam:.2f}"] = None
                continue
            if gamma_available and rdm_available:
                fit = fit_lambda_probe(
                    grids, PROBE_BEHAV, PROBE_NEURAL, lam, dl_sources,
                )
            elif rdm_available and lam == 1.0:
                # Sub-10 fallback: L_γ unavailable; only pure L_RDM at λ=1.0 is meaningful.
                # Build a single-loss fit on L_RDM and store at the λ=1.0 slot.
                single = fit_single_losses(grids, dl_sources)
                fit = single.get('L_RDM')
            else:
                fit = None
            per_lambda_fits[f"{lam:.2f}"] = fit

        per_subset.append({
            'subset': subset_list,
            'fits': per_lambda_fits,
            'gamma_available': gamma_available,
            'rdm_available': rdm_available,
        })
    return per_subset


def aggregate_outer_fold(per_subset, dl_sources):
    """For one outer fold, summarize the 15 inner-subset fits per (model, λ).

    Returns dict keyed by `model_label`, each with per-λ:
      {'param_median': ..., 'cov': ..., 'boundary_rate': ..., 'delta_vec': [...]}.
    The delta_vec is the forward-mapped 8-vec at the median parameter; this
    is what gets evaluated on the held-out HC for test loss.
    """
    rc_srcs = list(dl_sources.keys())
    out = {}

    for src in rc_srcs:
        label = f"rc_{src}"
        out[label] = {}
        for lam in LAMBDA_VALUES:
            lk = f"{lam:.2f}"
            params = []
            boundaries = []
            losses = []
            for ps in per_subset:
                ex = extract_rc_param(ps['fits'].get(lk), src)
                if ex is None:
                    params.append(None)
                    boundaries.append(None)
                    losses.append(None)
                else:
                    params.append(ex['g_best'])
                    boundaries.append(ex['boundary'])
                    losses.append(ex['loss_best'])
            stats = cov_and_summary(params)
            bdy_arr = [b for b in boundaries if b is not None]
            bdy_rate = float(np.mean(bdy_arr)) if bdy_arr else None
            out[label][lk] = {
                'param_median': stats['median'],
                'param_sd': stats['sd'],
                'cov': stats['cov'],
                'n_valid': stats['n_valid'],
                'boundary_rate': bdy_rate,
                'train_loss_median': safe_mean(losses),
            }

    out['2comp'] = {}
    for lam in LAMBDA_VALUES:
        lk = f"{lam:.2f}"
        bs_vals = []
        bc_vals = []
        norms = []
        boundaries = []
        losses = []
        for ps in per_subset:
            ex = extract_2comp_param(ps['fits'].get(lk))
            if ex is None:
                bs_vals.append(None)
                bc_vals.append(None)
                norms.append(None)
                boundaries.append(None)
                losses.append(None)
            else:
                bs_vals.append(ex['beta_s_best'])
                bc_vals.append(ex['beta_c_best'])
                norms.append(ex['norm'])
                boundaries.append(ex['boundary'])
                losses.append(ex['loss_best'])
        bs_stats = cov_and_summary(bs_vals)
        bc_stats = cov_and_summary(bc_vals)
        norm_stats = cov_and_summary(norms)
        bdy_arr = [b for b in boundaries if b is not None]
        bdy_rate = float(np.mean(bdy_arr)) if bdy_arr else None
        out['2comp'][lk] = {
            'beta_s_median': bs_stats['median'],
            'beta_s_sd': bs_stats['sd'],
            'beta_c_median': bc_stats['median'],
            'beta_c_sd': bc_stats['sd'],
            'norm_median': norm_stats['median'],
            'norm_cov': norm_stats['cov'],
            'cov': norm_stats['cov'],  # use norm CoV as composite CoV
            'n_valid': norm_stats['n_valid'],
            'boundary_rate': bdy_rate,
            'train_loss_median': safe_mean(losses),
        }
    return out


def test_eval_for_fold(
    per_fold_summary, hold_out, inner_pool, family, dl_sources,
    C_baseline, K, hc_amps_all, hc_jnd_all, hc_8afc_all,
):
    """For one outer fold, build test loss closures with HC_i as target and
    inner_pool as reference. Evaluate L_γ at the median(δθ) of the inner fits.

    Returns dict keyed by model label, each with per-λ test L_γ value (or None).

    Semantics: HC_i is target, inner_pool is HC reference. If fitted (g) /
    (β_s, β_c) captures a CVD-axis distortion, applying it to HC_i's behaviour
    should INCREASE the test L_γ value (HC's perception ≈ no distortion).
    Lower test_L_gamma ≈ fitted distortion looks HC-like → false-positive
    selection. Don't read "lower=better"; emit raw, interpret downstream.
    """
    if hold_out not in hc_amps_all:
        return None
    ho_amp = hc_amps_all[hold_out]
    ho_jnd = hc_jnd_all.get(hold_out)
    ho_8afc = hc_8afc_all.get(hold_out)
    if ho_jnd is None:
        # Can't compute L_γ; skip this fold.
        return None

    # Need LOCO W and ref baseline so make_loss_fns runs; LOCO/RDM won't
    # actually be evaluated for the test loss but we still build the full dict.
    ho_loco_W, _ = precompute_loco_W_within(ho_amp, C_baseline)
    inner_pool_amps = {h: hc_amps_all[h] for h in inner_pool if h in hc_amps_all}
    if len(inner_pool_amps) < 2:
        return None
    pool_jnd_subjs = [h for h in inner_pool if h in HC_JND_SUBJS]
    if not pool_jnd_subjs:
        return None
    pool_jnd_baseline, pool_jnd_sd = jnd_baseline_from_pool(pool_jnd_subjs)
    pool_hc_W, _ = precompute_hc_W(inner_pool_amps, C_baseline)

    test_loss_fns = make_loss_fns(
        ho_amp, ho_jnd, ho_8afc, ho_loco_W,
        inner_pool_amps, pool_jnd_baseline, pool_jnd_sd,
        pool_hc_W, C_baseline, K, family,
    )
    L_gamma_test = test_loss_fns.get('L_gamma')
    if L_gamma_test is None:
        return None

    rc_srcs = list(dl_sources.keys())
    test_out = {}
    for src in rc_srcs:
        label = f"rc_{src}"
        test_out[label] = {}
        for lam in LAMBDA_VALUES:
            lk = f"{lam:.2f}"
            stats = per_fold_summary.get(label, {}).get(lk, {})
            g_med = stats.get('param_median')
            if g_med is None or not np.isfinite(g_med):
                test_out[label][lk] = None
                continue
            try:
                delta = forward_rc(dl_sources[src], float(g_med), family)
                v = float(L_gamma_test(delta))
                test_out[label][lk] = v if np.isfinite(v) else None
            except Exception:
                test_out[label][lk] = None

    test_out['2comp'] = {}
    for lam in LAMBDA_VALUES:
        lk = f"{lam:.2f}"
        stats = per_fold_summary.get('2comp', {}).get(lk, {})
        bs_med = stats.get('beta_s_median')
        bc_med = stats.get('beta_c_median')
        if bs_med is None or bc_med is None:
            test_out['2comp'][lk] = None
            continue
        try:
            delta = forward_2comp(float(bs_med), float(bc_med), family)
            v = float(L_gamma_test(delta))
            test_out['2comp'][lk] = v if np.isfinite(v) else None
        except Exception:
            test_out['2comp'][lk] = None
    return test_out


def aggregate_cell(per_outer_fold_data, dl_sources):
    """Across the 7 outer folds, aggregate per (model, λ):
      - inner_cov_mean, inner_cov_median
      - test_L_gamma_mean, test_L_gamma_median
      - boundary_rate_mean
    """
    rc_srcs = list(dl_sources.keys())
    model_labels = [f"rc_{src}" for src in rc_srcs] + ['2comp']

    agg = {}
    for label in model_labels:
        agg[label] = {}
        for lam in LAMBDA_VALUES:
            lk = f"{lam:.2f}"
            covs = []
            param_meds = []
            train_losses = []
            test_losses = []
            bdy_rates = []
            beta_s_meds = []
            beta_c_meds = []
            for fold in per_outer_fold_data:
                summary = fold.get('summary', {}).get(label, {}).get(lk, {})
                test_v = fold.get('test', {})
                covs.append(summary.get('cov'))
                bdy_rates.append(summary.get('boundary_rate'))
                train_losses.append(summary.get('train_loss_median'))
                if label == '2comp':
                    beta_s_meds.append(summary.get('beta_s_median'))
                    beta_c_meds.append(summary.get('beta_c_median'))
                else:
                    param_meds.append(summary.get('param_median'))
                if test_v is not None:
                    test_losses.append(test_v.get(label, {}).get(lk))
                else:
                    test_losses.append(None)

            agg[label][lk] = {
                'inner_cov_mean': safe_mean(covs),
                'inner_cov_median': (float(np.median([c for c in covs if c is not None and np.isfinite(c)]))
                                     if any(c is not None and np.isfinite(c) for c in covs) else None),
                'boundary_rate_mean': safe_mean(bdy_rates),
                'train_loss_mean': safe_mean(train_losses),
                'test_L_gamma_mean': safe_mean(test_losses),
                'test_L_gamma_median': (float(np.median([t for t in test_losses if t is not None and np.isfinite(t)]))
                                         if any(t is not None and np.isfinite(t) for t in test_losses) else None),
                'n_outer_with_cov': sum(1 for c in covs if c is not None and np.isfinite(c)),
                'n_outer_with_test': sum(1 for t in test_losses if t is not None and np.isfinite(t)),
            }
            if label == '2comp':
                agg[label][lk]['beta_s_mean_of_medians'] = safe_mean(beta_s_meds)
                agg[label][lk]['beta_c_mean_of_medians'] = safe_mean(beta_c_meds)
            else:
                agg[label][lk]['param_mean_of_medians'] = safe_mean(param_meds)
    return agg


def process_cell(subject, family, roi, smoke=False):
    print(f"[NESTED-LOO CELL] {subject} {family} {roi}", flush=True)
    t_cell = time.time()
    K = ROI_K[roi]
    C_baseline = create_basis_full(K, basis_type='fe')[HUE_ANGLES.astype(int)]
    dl_sources = DELTA_LAMBDA_BY_FAMILY[family]

    # Load subject data (CVD or sub-10 normal-null)
    cvd_amp = load_amplitudes(subject, roi)
    try:
        cvd_jnd = load_jnd_per_pair(subject)
    except Exception:
        cvd_jnd = None
    try:
        cvd_8afc = load_8afc_per_color(subject)
    except Exception:
        cvd_8afc = None
    cvd_loco_W, _ = precompute_loco_W_within(cvd_amp, C_baseline)
    subject_data = {
        'amp': cvd_amp, 'jnd': cvd_jnd, '_8afc': cvd_8afc, 'loco_W': cvd_loco_W,
    }
    has_cvd_jnd = cvd_jnd is not None and len(
        [v for v in cvd_jnd.values() if v is not None]) > 0
    print(f"  cvd_jnd available: {has_cvd_jnd}", flush=True)

    # Load all 7 HC data once.
    hc_amps_all = load_hc_pool(roi)
    available_hc = list(hc_amps_all.keys())
    hc_jnd_all = {}
    hc_8afc_all = {}
    for h in HC_SUBJS:
        try:
            hc_jnd_all[h] = load_jnd_per_pair(h)
        except Exception:
            hc_jnd_all[h] = None
        try:
            hc_8afc_all[h] = load_8afc_per_color(h)
        except Exception:
            hc_8afc_all[h] = None

    outer_folds = HC_SUBJS if not smoke else HC_SUBJS[:1]

    per_outer_fold = []
    for hold_out in outer_folds:
        t_fold = time.time()
        inner_pool = [h for h in HC_SUBJS if h != hold_out and h in hc_amps_all]
        if len(inner_pool) < INNER_K:
            print(f"  fold {hold_out}: inner_pool size {len(inner_pool)} < {INNER_K}, SKIP", flush=True)
            continue

        per_subset = process_inner_for_outer(
            subject_data, cvd_amp, inner_pool, family, dl_sources,
            C_baseline, K, hc_amps_all,
        )
        if smoke:
            # Only keep first 3 inner subsets to verify pipeline works.
            per_subset = per_subset[:3]

        summary = aggregate_outer_fold(per_subset, dl_sources)
        test = test_eval_for_fold(
            summary, hold_out, inner_pool, family, dl_sources,
            C_baseline, K, hc_amps_all, hc_jnd_all, hc_8afc_all,
        )

        per_outer_fold.append({
            'hold_out_hc': hold_out,
            'inner_pool': inner_pool,
            'inner_n_subsets': len(per_subset),
            'summary': summary,
            'test': test,
            'fold_secs': round(time.time() - t_fold, 2),
        })
        print(f"  fold hold-out={hold_out}: {round(time.time() - t_fold, 1)}s "
              f"(test={'OK' if test else 'None'})", flush=True)

    aggregated = aggregate_cell(per_outer_fold, dl_sources)

    return {
        'subject': subject,
        'family': family,
        'roi': roi,
        'K': K,
        'available_hc': available_hc,
        'has_cvd_jnd': has_cvd_jnd,
        'design': {
            'outer_folds': len(outer_folds),
            'inner_k': INNER_K,
            'inner_subsets_per_fold': 'C(6,4)=15 (smoke=3)' if smoke else 'C(6,4)=15',
            'probe': 'gamma_plus_RDM',
            'probe_behav': list(PROBE_BEHAV),
            'probe_neural': list(PROBE_NEURAL),
            'lambda_values': LAMBDA_VALUES,
            'delta_lambda_sources': DELTA_LAMBDA_BY_FAMILY[family],
            'smoke': smoke,
        },
        'per_outer_fold': per_outer_fold,
        'aggregated': aggregated,
        'total_secs': round(time.time() - t_cell, 1),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--cell-idx', type=int, default=None,
                        help='SLURM array task index (0..11). If omitted, sequential local mode.')
    parser.add_argument('--smoke', action='store_true',
                        help='Smoke test: 1 outer fold, 3 inner subsets only.')
    args = parser.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    if args.cell_idx is not None:
        if args.cell_idx < 0 or args.cell_idx >= len(CELLS):
            print(f"ERROR: cell-idx {args.cell_idx} out of range [0, {len(CELLS) - 1}]")
            sys.exit(1)
        subject, family, roi = CELLS[args.cell_idx]
        print(f"[S7 NESTED-LOO ARRAY] cell {args.cell_idx}: {subject} {family} {roi}", flush=True)
        t0 = time.time()
        result = process_cell(subject, family, roi, smoke=args.smoke)
        suffix = '_smoke' if args.smoke else ''
        out_file = OUT_DIR / f"cell_{args.cell_idx:02d}_{subject}_{roi}{suffix}.json"
        with open(out_file, 'w') as f:
            json.dump(result, f, indent=2, default=str)
        print(f"\n[DONE] {out_file} ({round(time.time() - t0, 1)}s)", flush=True)
    else:
        print(f"[S7 NESTED-LOO LOCAL] {len(CELLS)} cells sequentially", flush=True)
        t0 = time.time()
        for idx, (subject, family, roi) in enumerate(CELLS):
            t_cell = time.time()
            result = process_cell(subject, family, roi, smoke=args.smoke)
            suffix = '_smoke' if args.smoke else ''
            out_file = OUT_DIR / f"cell_{idx:02d}_{subject}_{roi}{suffix}.json"
            with open(out_file, 'w') as f:
                json.dump(result, f, indent=2, default=str)
            print(f"  [{idx + 1}/{len(CELLS)}] {out_file} ({round(time.time() - t_cell, 1)}s)", flush=True)
        print(f"\n[DONE] Total {round(time.time() - t0, 1)}s", flush=True)


if __name__ == "__main__":
    main()
