#!/usr/bin/env python3
"""
Comprehensive Whitening Evaluation: Ceiling + SNR Analysis

This script tests the CRITICAL hypothesis:
    Does whitening improve DATA QUALITY (ceiling + SNR)?
    NOT just alignment performance!

Compares:
1. Noise ceiling: Raw vs Whitened
2. SNR (pattern, GLM, effective): Raw vs Whitened
3. RDM reliability with Procrustes: Raw vs Whitened
4. Comprehensive visualizations

Expected results:
- Raw ceiling: 0.65-0.70
- Whitened ceiling: 0.80-0.90 (+25-30%)
- SNR improvement: 50-150% (2-3× effective SNR)
- Procrustes performance: 0.21 → 0.38-0.42 (2× improvement)

Usage:
    python evaluate_whitening_ceiling_snr.py

Inputs:
    ../../phase1_preprocess_decoding/results/baseline/sub-{ID}/{ROI}/amplitudes_raw.npy
    ../../phase1_preprocess_decoding/results/baseline/sub-{ID}/{ROI}/residuals_2nd_level.npy

Outputs:
    results/whitening_ceiling_snr/comparison_all_subjects.json
    results/whitening_ceiling_snr/visualizations/*.png

Author: Generated by Claude Code (Updated Plan: Whitening as Preprocessing)
Date: 2026-01-30
"""

import numpy as np
from pathlib import Path
import json
import sys
from scipy.stats import spearmanr
import matplotlib.pyplot as plt

# Add utils to path
script_dir = Path(__file__).resolve().parent
sys.path.insert(0, str(script_dir / 'utils'))

from noise_ceiling import compute_split_half_reliability, visualize_split_half_distribution
from whitening import (
    estimate_noise_covariance,
    whiten_amplitudes,
    compute_pattern_snr,
    compute_glm_snr,
    compute_effective_snr,
    compare_snr_before_after_whitening,
    visualize_snr_comparison,
    visualize_whitening_effect
)
from crossnobis_ldw import compute_crossnobis_rdms_per_run

# Configuration
SUBJECTS = [f"{i:02d}" for i in range(1, 11)]
ROIS = ['V1', 'V2', 'V3', 'hV4']
BASE_DIR = Path(__file__).parent.parent.parent / "phase1_preprocess_decoding" / "results" / "baseline"
OUTPUT_DIR = Path(__file__).parent / "results" / "whitening_ceiling_snr"


def compute_rdm_correlation_per_run(amplitudes):
    """Compute RDM per run using Pearson correlation"""
    n_runs, n_colors, n_voxels = amplitudes.shape
    rdms = np.zeros((n_runs, n_colors, n_colors))

    for r in range(n_runs):
        patterns = amplitudes[r]
        corr_matrix = np.corrcoef(patterns)
        rdm = 1 - corr_matrix
        rdms[r] = rdm

    return rdms


def rdm_reliability_spearman(rdms):
    """Compute RDM reliability as mean Spearman correlation"""
    n_runs, n_colors, _ = rdms.shape
    triu_idx = np.triu_indices(n_colors, k=1)

    correlations = []
    for i in range(n_runs):
        for j in range(i+1, n_runs):
            vec_i = rdms[i][triu_idx]
            vec_j = rdms[j][triu_idx]
            r, _ = spearmanr(vec_i, vec_j)
            correlations.append(r)

    return np.mean(correlations)


def apply_procrustes_simple(amplitudes):
    """
    Simple Procrustes alignment (center + orthogonal rotation)

    This is a simplified version for testing.
    Uses first run as reference, aligns others to it.
    """
    from scipy.linalg import orthogonal_procrustes

    n_runs, n_colors, n_voxels = amplitudes.shape
    aligned = np.zeros_like(amplitudes)

    # Reference: first run
    reference = amplitudes[0].copy()
    reference_centered = reference - reference.mean(axis=0)
    aligned[0] = reference_centered

    # Align other runs to reference
    for run in range(1, n_runs):
        target = amplitudes[run].copy()
        target_centered = target - target.mean(axis=0)

        # Procrustes: find rotation R
        R, _ = orthogonal_procrustes(target_centered, reference_centered)

        # Apply rotation
        aligned[run] = target_centered @ R

    return aligned


def evaluate_single_roi_whitening(subject, roi, verbose=True):
    """
    Comprehensive evaluation: Raw vs Whitened data

    Tests CRITICAL hypothesis: Does whitening improve data quality (ceiling + SNR)?

    Returns:
        dict or None: Comprehensive metrics if successful
    """
    result_dir = BASE_DIR / f"sub-{subject}" / roi

    # Check files
    raw_path = result_dir / "amplitudes_raw.npy"
    residuals_path = result_dir / "residuals_2nd_level.npy"

    if not raw_path.exists():
        if verbose:
            print(f"⚠️  Skip: sub-{subject}/{roi} (amplitudes_raw.npy missing)")
        return None

    try:
        # Load data
        amplitudes_raw = np.load(raw_path)
        n_runs, n_colors, n_voxels = amplitudes_raw.shape

        # Load residuals (optional - use amplitudes if not available)
        use_residuals = residuals_path.exists()
        if use_residuals:
            residuals = np.load(residuals_path, allow_pickle=True)
            if isinstance(residuals, np.ndarray) and residuals.dtype == object:
                residuals = residuals.item()  # Convert to dict
                residuals = np.vstack([residuals[run] for run in sorted(residuals.keys())])
        else:
            # Fallback: estimate noise from amplitudes themselves
            # Use run-to-run variability as noise estimate
            residuals = amplitudes_raw.reshape(-1, n_voxels)
            if verbose:
                print(f"⚠️  Residuals not found - using amplitudes for noise estimation")

        if verbose:
            print(f"\n{'='*60}")
            print(f"Evaluating: sub-{subject}/{roi}")
            print(f"Shape: {n_runs} runs × {n_colors} colors × {n_voxels} voxels")
            if use_residuals:
                print(f"Residuals: {residuals.shape} (from GLM)")
            else:
                print(f"Residuals: {residuals.shape} (estimated from amplitudes)")

        # ========================================
        # STEP 1: Estimate noise covariance
        # ========================================
        if verbose:
            print(f"\n--- Step 1: Noise Covariance Estimation ---")
            if not use_residuals:
                print(f"Note: Using amplitude variability as noise proxy")

        noise_cov, shrinkage = estimate_noise_covariance(residuals, method='ledoit_wolf')

        if verbose:
            print(f"Shrinkage parameter: {shrinkage:.3f}")
            print(f"(0=empirical, 1=diagonal, ~0.3-0.4=typical for fMRI)")

        # ========================================
        # STEP 2: Apply whitening
        # ========================================
        if verbose:
            print(f"\n--- Step 2: Whitening Transformation ---")

        amplitudes_whitened, whitening_matrix = whiten_amplitudes(amplitudes_raw, noise_cov)

        if verbose:
            print(f"Whitened data shape: {amplitudes_whitened.shape}")

        # ========================================
        # STEP 3: Noise Ceiling Comparison
        # ========================================
        if verbose:
            print(f"\n--- Step 3: Noise Ceiling (Split-Half) ---")

        # Raw data ceiling
        ceiling_raw = compute_split_half_reliability(amplitudes_raw, n_iterations=1000)

        # Whitened data ceiling
        ceiling_whitened = compute_split_half_reliability(amplitudes_whitened, n_iterations=1000)

        ceiling_improvement = ceiling_whitened['corrected'] - ceiling_raw['corrected']
        ceiling_improvement_pct = (ceiling_whitened['corrected'] / ceiling_raw['corrected'] - 1) * 100

        if verbose:
            print(f"Raw ceiling:      {ceiling_raw['corrected']:.3f} "
                  f"[{ceiling_raw['ci_lower']:.3f}, {ceiling_raw['ci_upper']:.3f}]")
            print(f"Whitened ceiling: {ceiling_whitened['corrected']:.3f} "
                  f"[{ceiling_whitened['ci_lower']:.3f}, {ceiling_whitened['ci_upper']:.3f}]")
            print(f"Improvement: {ceiling_improvement:+.3f} ({ceiling_improvement_pct:+.1f}%)")

        # ========================================
        # STEP 4: SNR Comparison
        # ========================================
        if verbose:
            print(f"\n--- Step 4: SNR Analysis ---")

        # Pass residuals only if from GLM (not from amplitudes fallback)
        residuals_for_snr = residuals if use_residuals else None
        snr_comparison = compare_snr_before_after_whitening(
            amplitudes_raw,
            amplitudes_whitened,
            residuals_for_snr,
            noise_cov
        )

        # ========================================
        # STEP 5: RDM Reliability with Procrustes
        # ========================================
        if verbose:
            print(f"\n--- Step 5: RDM Reliability (with Procrustes) ---")

        # Raw + Procrustes
        amp_raw_proc = apply_procrustes_simple(amplitudes_raw)
        rdms_raw_proc = compute_rdm_correlation_per_run(amp_raw_proc)
        reliability_raw_proc = rdm_reliability_spearman(rdms_raw_proc)

        # Whitened + Procrustes
        amp_white_proc = apply_procrustes_simple(amplitudes_whitened)
        rdms_white_proc = compute_rdm_correlation_per_run(amp_white_proc)
        reliability_white_proc = rdm_reliability_spearman(rdms_white_proc)

        reliability_improvement = reliability_white_proc - reliability_raw_proc
        reliability_improvement_pct = (reliability_white_proc / reliability_raw_proc - 1) * 100

        if verbose:
            print(f"Raw + Procrustes:      {reliability_raw_proc:.3f} "
                  f"({reliability_raw_proc/ceiling_raw['corrected']*100:.1f}% of ceiling)")
            print(f"Whitened + Procrustes: {reliability_white_proc:.3f} "
                  f"({reliability_white_proc/ceiling_whitened['corrected']*100:.1f}% of ceiling)")
            print(f"Improvement: {reliability_improvement:+.3f} ({reliability_improvement_pct:+.1f}%)")

        # ========================================
        # Compile results
        # ========================================
        results = {
            # Metadata
            'subject': subject,
            'roi': roi,
            'n_voxels': int(n_voxels),
            'n_runs': int(n_runs),

            # Noise covariance
            'shrinkage': float(shrinkage),

            # Noise ceiling
            'ceiling_raw': float(ceiling_raw['corrected']),
            'ceiling_raw_ci': [float(ceiling_raw['ci_lower']), float(ceiling_raw['ci_upper'])],
            'ceiling_whitened': float(ceiling_whitened['corrected']),
            'ceiling_whitened_ci': [float(ceiling_whitened['ci_lower']), float(ceiling_whitened['ci_upper'])],
            'ceiling_improvement': float(ceiling_improvement),
            'ceiling_improvement_pct': float(ceiling_improvement_pct),

            # SNR metrics
            'pattern_snr_raw': float(snr_comparison['pattern_snr']['raw']['pattern_snr']),
            'pattern_snr_whitened': float(snr_comparison['pattern_snr']['whitened']['pattern_snr']),
            'pattern_snr_improvement_pct': float(snr_comparison['pattern_snr']['improvement_pct']),

            'glm_snr_raw': float(snr_comparison['glm_snr']['raw']['glm_snr']),
            'glm_snr_whitened': float(snr_comparison['glm_snr']['whitened']['glm_snr']),
            'glm_snr_improvement_pct': float(snr_comparison['glm_snr']['improvement_pct']),

            'effective_snr_raw': float(snr_comparison['effective_snr']['raw']['effective_snr']),
            'effective_snr_whitened': float(snr_comparison['effective_snr']['whitened']['effective_snr']),
            'effective_snr_improvement_pct': float(snr_comparison['effective_snr']['improvement_pct']),

            # RDM reliability
            'rdm_reliability_raw_proc': float(reliability_raw_proc),
            'rdm_reliability_white_proc': float(reliability_white_proc),
            'rdm_reliability_improvement': float(reliability_improvement),
            'rdm_reliability_improvement_pct': float(reliability_improvement_pct),

            # Performance relative to ceiling
            'pct_ceiling_raw': float(reliability_raw_proc / ceiling_raw['corrected'] * 100),
            'pct_ceiling_whitened': float(reliability_white_proc / ceiling_whitened['corrected'] * 100),

            # Full SNR comparison (for detailed analysis)
            'snr_comparison_full': snr_comparison
        }

        if verbose:
            print(f"\n{'='*60}")
            print(f"✓ sub-{subject}/{roi} completed")
            print(f"  Key finding: Ceiling {ceiling_raw['corrected']:.3f} → {ceiling_whitened['corrected']:.3f} "
                  f"({ceiling_improvement_pct:+.1f}%)")
            print(f"  Performance: {reliability_raw_proc:.3f} → {reliability_white_proc:.3f} "
                  f"({reliability_improvement_pct:+.1f}%)")

        return results

    except Exception as e:
        print(f"❌ sub-{subject}/{roi}: {e}")
        import traceback
        traceback.print_exc()
        return None


def create_comprehensive_visualizations(all_results, output_dir):
    """Generate comprehensive visualizations"""
    viz_dir = output_dir / "visualizations"
    viz_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n{'='*60}")
    print("Generating Comprehensive Visualizations")
    print(f"{'='*60}")

    # 1. Ceiling improvement per ROI
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    axes = axes.flatten()

    for idx, roi in enumerate(ROIS):
        ax = axes[idx]
        roi_results = [v for v in all_results.values() if v['roi'] == roi]

        if not roi_results:
            continue

        subjects = [v['subject'] for v in roi_results]
        ceiling_raw = [v['ceiling_raw'] for v in roi_results]
        ceiling_white = [v['ceiling_whitened'] for v in roi_results]

        x = np.arange(len(subjects))
        width = 0.35

        ax.bar(x - width/2, ceiling_raw, width, label='Raw', color='coral', alpha=0.8)
        ax.bar(x + width/2, ceiling_white, width, label='Whitened', color='steelblue', alpha=0.8)

        ax.set_xlabel('Subject', fontsize=10, fontweight='bold')
        ax.set_ylabel('Noise Ceiling (r)', fontsize=10, fontweight='bold')
        ax.set_title(f'{roi}: Ceiling Improvement', fontsize=12, fontweight='bold')
        ax.set_xticks(x)
        ax.set_xticklabels([f's{s}' for s in subjects], fontsize=8)
        ax.legend(loc='upper left', fontsize=9)
        ax.grid(axis='y', alpha=0.3, linestyle=':')

        # Mean improvement annotation
        mean_improvement_pct = np.mean([v['ceiling_improvement_pct'] for v in roi_results])
        ax.text(0.5, 0.95, f'Mean: +{mean_improvement_pct:.1f}%',
               transform=ax.transAxes, ha='center', va='top',
               fontsize=10, fontweight='bold', color='green',
               bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))

    plt.tight_layout()
    plt.savefig(viz_dir / "ceiling_improvement_all_rois.png", dpi=300, bbox_inches='tight')
    plt.close()
    print(f"✓ Saved: ceiling_improvement_all_rois.png")

    # 2. SNR improvement summary
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

    for roi, color in zip(ROIS, ['red', 'orange', 'green', 'blue']):
        roi_results = [v for v in all_results.values() if v['roi'] == roi]

        if not roi_results:
            continue

        pattern_snr_improvements = [v['pattern_snr_improvement_pct'] for v in roi_results]
        effective_snr_improvements = [v['effective_snr_improvement_pct'] for v in roi_results]

        ax1.scatter([roi] * len(pattern_snr_improvements), pattern_snr_improvements,
                   s=80, alpha=0.6, color=color, label=roi)
        ax2.scatter([roi] * len(effective_snr_improvements), effective_snr_improvements,
                   s=80, alpha=0.6, color=color, label=roi)

    ax1.axhline(0, color='black', linestyle='--', linewidth=1)
    ax1.set_ylabel('Pattern SNR Improvement (%)', fontsize=12, fontweight='bold')
    ax1.set_title('Pattern SNR: Whitening Effect', fontsize=14, fontweight='bold')
    ax1.grid(alpha=0.3, linestyle=':')
    ax1.legend(loc='upper left', fontsize=10)

    ax2.axhline(0, color='black', linestyle='--', linewidth=1)
    ax2.set_ylabel('Effective SNR Improvement (%)', fontsize=12, fontweight='bold')
    ax2.set_title('Effective SNR: Whitening Effect', fontsize=14, fontweight='bold')
    ax2.grid(alpha=0.3, linestyle=':')
    ax2.legend(loc='upper left', fontsize=10)

    plt.tight_layout()
    plt.savefig(viz_dir / "snr_improvement_summary.png", dpi=300, bbox_inches='tight')
    plt.close()
    print(f"✓ Saved: snr_improvement_summary.png")

    # 3. Performance vs ceiling scatter
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

    for roi, color in zip(ROIS, ['red', 'orange', 'green', 'blue']):
        roi_results = [v for v in all_results.values() if v['roi'] == roi]

        if not roi_results:
            continue

        # Raw
        ceiling_raw = [v['ceiling_raw'] for v in roi_results]
        perf_raw = [v['rdm_reliability_raw_proc'] for v in roi_results]
        ax1.scatter(ceiling_raw, perf_raw, s=100, alpha=0.7, color=color, label=roi)

        # Whitened
        ceiling_white = [v['ceiling_whitened'] for v in roi_results]
        perf_white = [v['rdm_reliability_white_proc'] for v in roi_results]
        ax2.scatter(ceiling_white, perf_white, s=100, alpha=0.7, color=color, label=roi)

    # Diagonal lines
    for ax, title in zip([ax1, ax2], ['Raw Data', 'Whitened Data']):
        max_val = 1.0
        ax.plot([0, max_val], [0, max_val], 'k--', linewidth=2, label='Perfect (100%)')
        ax.plot([0, max_val], [0, max_val*0.5], 'gray', linestyle=':', linewidth=2, label='50% ceiling')

        ax.set_xlabel('Noise Ceiling (r)', fontsize=12, fontweight='bold')
        ax.set_ylabel('Observed Performance (r)', fontsize=12, fontweight='bold')
        ax.set_title(f'Performance vs Ceiling: {title}', fontsize=14, fontweight='bold')
        ax.legend(loc='upper left', fontsize=10)
        ax.grid(alpha=0.3, linestyle=':')
        ax.set_xlim(0, max_val)
        ax.set_ylim(0, max_val)
        ax.set_aspect('equal', adjustable='box')

    plt.tight_layout()
    plt.savefig(viz_dir / "performance_vs_ceiling_comparison.png", dpi=300, bbox_inches='tight')
    plt.close()
    print(f"✓ Saved: performance_vs_ceiling_comparison.png")

    print(f"\n✓ All visualizations saved to {viz_dir}")


def main():
    """Main evaluation pipeline"""

    print("="*80)
    print("WHITENING CEILING + SNR EVALUATION")
    print("="*80)
    print("Testing CRITICAL hypothesis:")
    print("  Does whitening improve DATA QUALITY (ceiling + SNR)?")
    print("")
    print(f"Subjects: {len(SUBJECTS)} (sub-01 ~ sub-10)")
    print(f"ROIs: {len(ROIS)} (V1, V2, V3, hV4)")
    print(f"Total: {len(SUBJECTS) * len(ROIS)} pairs")
    print("")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    all_results = {}

    # Evaluate each subject-ROI
    for subject in SUBJECTS:
        for roi in ROIS:
            result = evaluate_single_roi_whitening(subject, roi, verbose=True)

            if result is not None:
                key = f"sub-{subject}_{roi}"
                all_results[key] = result

    print(f"\n{'='*80}")
    print(f"✓ Completed {len(all_results)} / {len(SUBJECTS) * len(ROIS)} pairs")
    print(f"{'='*80}")

    # Summary statistics
    print(f"\n{'='*80}")
    print("SUMMARY STATISTICS")
    print(f"{'='*80}")

    summary = {}
    for roi in ROIS:
        roi_results = [v for v in all_results.values() if v['roi'] == roi]

        if not roi_results:
            continue

        summary[roi] = {
            'n_subjects': len(roi_results),
            'ceiling_raw_mean': float(np.mean([v['ceiling_raw'] for v in roi_results])),
            'ceiling_whitened_mean': float(np.mean([v['ceiling_whitened'] for v in roi_results])),
            'ceiling_improvement_pct_mean': float(np.mean([v['ceiling_improvement_pct'] for v in roi_results])),
            'pattern_snr_improvement_pct_mean': float(np.mean([v['pattern_snr_improvement_pct'] for v in roi_results])),
            'effective_snr_improvement_pct_mean': float(np.mean([v['effective_snr_improvement_pct'] for v in roi_results])),
            'rdm_reliability_raw_mean': float(np.mean([v['rdm_reliability_raw_proc'] for v in roi_results])),
            'rdm_reliability_whitened_mean': float(np.mean([v['rdm_reliability_white_proc'] for v in roi_results])),
            'performance_improvement_pct_mean': float(np.mean([v['rdm_reliability_improvement_pct'] for v in roi_results]))
        }

        print(f"\n{roi}:")
        print(f"  Ceiling:    {summary[roi]['ceiling_raw_mean']:.3f} → {summary[roi]['ceiling_whitened_mean']:.3f} "
              f"({summary[roi]['ceiling_improvement_pct_mean']:+.1f}%)")
        print(f"  Pattern SNR improvement: {summary[roi]['pattern_snr_improvement_pct_mean']:+.1f}%")
        print(f"  Effective SNR improvement: {summary[roi]['effective_snr_improvement_pct_mean']:+.1f}%")
        print(f"  Performance: {summary[roi]['rdm_reliability_raw_mean']:.3f} → {summary[roi]['rdm_reliability_whitened_mean']:.3f} "
              f"({summary[roi]['performance_improvement_pct_mean']:+.1f}%)")

    # Save results
    output_file = OUTPUT_DIR / "comparison_all_subjects.json"
    output_data = {
        'individual_results': all_results,
        'summary_by_roi': summary
    }

    with open(output_file, 'w') as f:
        json.dump(output_data, f, indent=2)

    print(f"\n✓ Results saved to {output_file}")

    # Generate visualizations
    create_comprehensive_visualizations(all_results, OUTPUT_DIR)

    print(f"\n{'='*80}")
    print("✓ EVALUATION COMPLETE")
    print(f"{'='*80}")
    print("\nKEY FINDINGS:")
    print(f"  1. Noise ceiling improvement: {np.mean([s['ceiling_improvement_pct_mean'] for s in summary.values()]):+.1f}% (average)")
    print(f"  2. SNR improvement: {np.mean([s['effective_snr_improvement_pct_mean'] for s in summary.values()]):+.1f}% (average)")
    print(f"  3. Performance improvement: {np.mean([s['performance_improvement_pct_mean'] for s in summary.values()]):+.1f}% (average)")
    print("\nCONCLUSION:")
    avg_ceiling_improvement = np.mean([s['ceiling_improvement_pct_mean'] for s in summary.values()])
    if avg_ceiling_improvement > 15:
        print("  ✓ Whitening SUBSTANTIALLY improves data quality!")
        print("  → RECOMMENDATION: Adopt whitening as standard preprocessing")
    elif avg_ceiling_improvement > 5:
        print("  ✓ Whitening moderately improves data quality")
        print("  → RECOMMENDATION: Use whitening for low-SNR subjects/ROIs")
    else:
        print("  ⚠️  Whitening has minimal effect")
        print("  → RECOMMENDATION: Noise correlation may be low already")


if __name__ == '__main__':
    main()
