# 01 — Discrimination preserved + cross-decoding (E1)
Results §1, Fig 2A, S14.

**Provenance.** Built by `~/.claude/skills/repro-notebook/SKILL.md` (Phase 3).
Companion docs: `docs/PAPER/repro/{MANIFEST.md, MAP.md, REPORT.md}`.
Target paper: `docs/PAPER/main.tex` → `Results/results_v4.tex`.
Helpers: `docs/PAPER/repro/_repro_util.py`.

**Modes.** `RECOMPUTE` = computed locally from C010 amplitudes. `LOAD+VERIFY` =
read the committed result JSON and compare to the printed paper value. SRM/BrainIAK
numbers are read from committed JSON (no MPI in this kernel).

**Source & code map**

| id | reported | source JSON | mode |
|---|---|---|---|
| E1.1 | both CVD > 0.125 every ROI | `phase3_decoder_comparing/.../cvd_cross_decoding_procrustes.json` | LOAD+VERIFY |
| E1.2 | MannWhitney p=0.668 | `phase3_decoder_comparing/results/loro/srm/validation/cross_subject_generalization.json` | LOAD+VERIFY |
| E1.3 | hV4 single-case p=0.142 | `_compute_paper_stats.py` (stdout only) | ⚠ FLAG |

In [1]:
import sys, os, json
sys.path.insert(0, os.path.abspath('.'))   # docs/PAPER/repro
import numpy as np
import _repro_util as U
U._RESULTS.clear()   # fresh check log per notebook
print("repo:", U.REPO)

repo: /Users/jinilkim/Library/CloudStorage/OneDrive-Personal/Projects/colorBlind_analysis


### E1.1 — 8-class LORO discrimination exceeds 0.125 chance at every ROI (both CVD)

In [2]:
j = U.load_json(U.DEC / "model_comparison_validation/results/cvd_cross_decoding/cvd_cross_decoding_procrustes.json")
res = j["results"]
allpass = True
for roi in ["V1", "V2", "V3", "V4"]:
    ch = res[roi]["chance"]
    for s in ["sub-08", "sub-09"]:
        acc = res[roi]["cvd_cross"][s]
        ok = U.check(f"E1.1 {roi} {s} acc>chance", acc, ch, mode="ge")
        allpass = allpass and ok
print("all ROI/subj above chance:", allpass)

[OK ] E1.1 V1 sub-08 acc>chance: produced=1.0  reported=0.125
[OK ] E1.1 V1 sub-09 acc>chance: produced=0.5  reported=0.125
[OK ] E1.1 V2 sub-08 acc>chance: produced=0.75  reported=0.125
[OK ] E1.1 V2 sub-09 acc>chance: produced=0.875  reported=0.125
[OK ] E1.1 V3 sub-08 acc>chance: produced=0.75  reported=0.125
[OK ] E1.1 V3 sub-09 acc>chance: produced=0.875  reported=0.125
[OK ] E1.1 V4 sub-08 acc>chance: produced=0.75  reported=0.125
[OK ] E1.1 V4 sub-09 acc>chance: produced=0.75  reported=0.125
all ROI/subj above chance: True


*Target:* both CVD exceed exact-accuracy chance 1/8=0.125 at V1–hV4.

### E1.2 — cross-subject generalization Mann–Whitney p=0.668 (LDA, all ROIs pooled)

In [3]:
j = U.load_json(U.DEC / "results/loro/srm/validation/cross_subject_generalization.json")
p = j["LDA"]["difference"]["p_value"]
U.check("E1.2 MannWhitney p", p, 0.668, ndigits=3)
print("hc_to_hc mean=%.3f  hc_to_cvd mean=%.3f" % (j["LDA"]["hc_to_hc"]["mean"], j["LDA"]["hc_to_cvd"]["mean"]))

[OK ] E1.2 MannWhitney p: produced=0.6681132001922938  reported=0.668
hc_to_hc mean=0.635  hc_to_cvd mean=0.665


*Target:* p=0.668 (21 HC-to-HC vs 14 HC-to-CVD pairs).

### E1.3 — within-ROI hV4 single-case p=0.142  ⚠ FLAG
No committed output: produced only as stdout by `_compute_paper_stats.py`. Marked
not-cleanly-reproducible; regenerate by running that script. Recorded as a flag.

In [4]:
U.check("E1.3 hV4 single-case p (FLAG: stdout-only)", float("nan"), 0.142)

[XX ] E1.3 hV4 single-case p (FLAG: stdout-only): produced=nan  reported=0.142


In [5]:
U.summary()


=== 9/10 checks reproduced ===
  MISMATCH E1.3 hV4 single-case p (FLAG: stdout-only): produced=nan reported=0.142
