#!/usr/bin/env python3
"""
Visualize Color Geometry and Voxel Patterns

Generates color-space and voxel-level visualizations:
  1. Voxel-Color Amplitude Heatmaps (before/after Procrustes)
  2. RDM Matrices per run (before/after)
  3. Color Space Embedding (MDS)
  4. Voxel Tuning Curves (example voxels)

Usage:
    python visualize_color_geometry.py --subject 01 --roi V1

Author: Generated by Claude Code
Date: 2026-01-30
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import argparse
from sklearn.manifold import MDS
from scipy.stats import zscore

# Configuration
BASE_DIR = Path(__file__).parent / "results" / "baseline"

# Color names and RGB values (for visualization)
COLOR_NAMES = ['Red', 'Orange', 'Yellow', 'Green', 'Cyan', 'Blue', 'Purple', 'Magenta']
COLOR_RGB = [
    [1.0, 0.0, 0.0],    # Red
    [1.0, 0.5, 0.0],    # Orange
    [1.0, 1.0, 0.0],    # Yellow
    [0.0, 1.0, 0.0],    # Green
    [0.0, 1.0, 1.0],    # Cyan
    [0.0, 0.0, 1.0],    # Blue
    [0.5, 0.0, 1.0],    # Purple
    [1.0, 0.0, 1.0]     # Magenta
]


def load_subject_data(subject, roi):
    """Load amplitudes for a subject-ROI pair"""
    result_dir = BASE_DIR / f"sub-{subject}" / roi

    raw_path = result_dir / "amplitudes_raw.npy"
    procrustes_path = result_dir / "amplitudes_procrustes.npy"

    if not raw_path.exists():
        raise FileNotFoundError(f"Missing: {raw_path}")
    if not procrustes_path.exists():
        raise FileNotFoundError(f"Missing: {procrustes_path}")

    amplitudes_raw = np.load(raw_path)
    amplitudes_procrustes = np.load(procrustes_path)

    return amplitudes_raw, amplitudes_procrustes


def plot_voxel_color_heatmaps(amplitudes_raw, amplitudes_procrustes, output_dir, subject, roi):
    """
    Figure 1: Voxel-Color Amplitude Heatmaps

    2 panels: Before and After Procrustes
    Heatmap: voxels (rows) × colors (columns)
    """
    n_runs, n_colors, n_voxels = amplitudes_raw.shape

    # Average across runs
    amp_raw_mean = amplitudes_raw.mean(axis=0)  # (8, n_voxels)
    amp_proc_mean = amplitudes_procrustes.mean(axis=0)

    # Z-score per voxel (for better visualization)
    amp_raw_z = zscore(amp_raw_mean, axis=0)  # Z-score across colors
    amp_proc_z = zscore(amp_proc_mean, axis=0)

    # Transpose for heatmap (voxels × colors)
    amp_raw_z = amp_raw_z.T  # (n_voxels, 8)
    amp_proc_z = amp_proc_z.T

    # Sort voxels by peak color (for clustering visualization)
    peak_colors_raw = np.argmax(amp_raw_z, axis=1)
    peak_colors_proc = np.argmax(amp_proc_z, axis=1)

    sort_idx_raw = np.argsort(peak_colors_raw)
    sort_idx_proc = np.argsort(peak_colors_proc)

    # Create figure
    fig, axes = plt.subplots(1, 2, figsize=(16, 10))

    # Panel A: Before Procrustes
    ax = axes[0]
    im = ax.imshow(amp_raw_z[sort_idx_raw], aspect='auto', cmap='RdBu_r', vmin=-3, vmax=3)
    ax.set_xlabel('Color', fontsize=14)
    ax.set_ylabel('Voxel (sorted by peak color)', fontsize=14)
    ax.set_title(f'A. Before Procrustes\n{subject} {roi} (n={n_voxels} voxels)', fontsize=16)
    ax.set_xticks(range(8))
    ax.set_xticklabels(COLOR_NAMES, rotation=45, ha='right')

    # Color bars on top
    for i in range(8):
        ax.axvline(i - 0.5, color='black', linewidth=0.5, alpha=0.3)
        # Color bar
        rect = plt.Rectangle((i - 0.45, ax.get_ylim()[1] * 1.01), 0.9, ax.get_ylim()[1] * 0.03,
                            facecolor=COLOR_RGB[i], edgecolor='black', clip_on=False)
        ax.add_patch(rect)

    plt.colorbar(im, ax=ax, label='Amplitude (z-scored)')

    # Panel B: After Procrustes
    ax = axes[1]
    im = ax.imshow(amp_proc_z[sort_idx_proc], aspect='auto', cmap='RdBu_r', vmin=-3, vmax=3)
    ax.set_xlabel('Color', fontsize=14)
    ax.set_ylabel('Voxel (sorted by peak color)', fontsize=14)
    ax.set_title(f'B. After Procrustes\n{subject} {roi} (n={n_voxels} voxels)', fontsize=16)
    ax.set_xticks(range(8))
    ax.set_xticklabels(COLOR_NAMES, rotation=45, ha='right')

    for i in range(8):
        ax.axvline(i - 0.5, color='black', linewidth=0.5, alpha=0.3)
        rect = plt.Rectangle((i - 0.45, ax.get_ylim()[1] * 1.01), 0.9, ax.get_ylim()[1] * 0.03,
                            facecolor=COLOR_RGB[i], edgecolor='black', clip_on=False)
        ax.add_patch(rect)

    plt.colorbar(im, ax=ax, label='Amplitude (z-scored)')

    plt.tight_layout()

    output_file = output_dir / f'voxel_color_heatmap_sub-{subject}_{roi}.png'
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"✓ Saved: {output_file}")

    plt.close()


def compute_rdm(patterns, debug=False):
    """
    Compute RDM (1 - correlation)

    Args:
        patterns: (n_colors, n_voxels) - Color patterns
        debug: If True, print diagnostic info
    """
    corr = np.corrcoef(patterns)
    rdm = 1 - corr

    if debug:
        print(f"  Pattern shape: {patterns.shape}")
        print(f"  Correlation range: [{corr.min():.4f}, {corr.max():.4f}]")
        print(f"  RDM range: [{rdm.min():.4f}, {rdm.max():.4f}]")
        print(f"  RDM mean (off-diagonal): {rdm[np.triu_indices_from(rdm, k=1)].mean():.4f}")

    return rdm


def plot_rdm_matrices(amplitudes_raw, amplitudes_procrustes, output_dir, subject, roi):
    """
    Figure 2: RDM Matrices per run (Before/After)

    2×6 panel: 6 runs × 2 conditions (before/after)
    """
    n_runs, n_colors, n_voxels = amplitudes_raw.shape

    fig, axes = plt.subplots(2, 6, figsize=(20, 8))

    # Before Procrustes (row 0)
    for run in range(n_runs):
        ax = axes[0, run]
        patterns = amplitudes_raw[run]  # (8, n_voxels)

        # Debug first run
        if run == 0:
            print(f"  Debug: Before Procrustes (Run 1)")
            rdm = compute_rdm(patterns, debug=True)
        else:
            rdm = compute_rdm(patterns)

        im = ax.imshow(rdm, cmap='viridis', vmin=0, vmax=2)
        ax.set_title(f'Run {run+1}', fontsize=10)
        ax.set_xticks(range(8))
        ax.set_yticks(range(8))

        if run == 0:
            ax.set_ylabel('Before\nProcrustes', fontsize=12)
            ax.set_yticklabels(COLOR_NAMES, fontsize=8)
        else:
            ax.set_yticklabels([])

        ax.set_xticklabels(COLOR_NAMES, rotation=90, fontsize=8)

    # After Procrustes (row 1)
    for run in range(n_runs):
        ax = axes[1, run]
        patterns = amplitudes_procrustes[run]

        # Debug first run
        if run == 0:
            print(f"  Debug: After Procrustes (Run 1)")
            rdm = compute_rdm(patterns, debug=True)
        else:
            rdm = compute_rdm(patterns)

        im = ax.imshow(rdm, cmap='viridis', vmin=0, vmax=2)

        if run == 0:
            ax.set_ylabel('After\nProcrustes', fontsize=12)
            ax.set_yticklabels(COLOR_NAMES, fontsize=8)
        else:
            ax.set_yticklabels([])

        ax.set_xticks(range(8))
        ax.set_yticks(range(8))
        ax.set_xticklabels(COLOR_NAMES, rotation=90, fontsize=8)

    # Add colorbar
    fig.subplots_adjust(right=0.92)
    cbar_ax = fig.add_axes([0.94, 0.15, 0.02, 0.7])
    fig.colorbar(im, cax=cbar_ax, label='Dissimilarity (1 - correlation)')

    fig.suptitle(f'RDM Matrices: {subject} {roi}', fontsize=16, y=0.98)

    plt.tight_layout()

    output_file = output_dir / f'rdm_matrices_per_run_sub-{subject}_{roi}.png'
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"✓ Saved: {output_file}")

    plt.close()


def plot_color_space_embedding(amplitudes_raw, amplitudes_procrustes, output_dir, subject, roi):
    """
    Figure 3: Color Space Embedding (MDS)

    2 panels: Before and After Procrustes
    Each panel: 6 runs overlaid with different transparency
    """
    n_runs, n_colors, n_voxels = amplitudes_raw.shape

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    # Panel A: Before Procrustes
    ax = axes[0]

    for run in range(n_runs):
        patterns = amplitudes_raw[run]  # (8, n_voxels)
        rdm = compute_rdm(patterns)

        # MDS embedding
        mds = MDS(n_components=2, dissimilarity='precomputed', random_state=42)
        embedding = mds.fit_transform(rdm)

        # Plot with transparency
        for i in range(n_colors):
            ax.scatter(embedding[i, 0], embedding[i, 1],
                      c=[COLOR_RGB[i]], s=150, alpha=0.4,
                      edgecolors='black', linewidths=0.5)

    # Add labels (once)
    rdm_mean = np.mean([compute_rdm(amplitudes_raw[r]) for r in range(n_runs)], axis=0)
    mds = MDS(n_components=2, dissimilarity='precomputed', random_state=42)
    embedding_mean = mds.fit_transform(rdm_mean)

    for i in range(n_colors):
        ax.text(embedding_mean[i, 0], embedding_mean[i, 1], COLOR_NAMES[i],
               fontsize=10, ha='center', va='center',
               bbox=dict(boxstyle='round', facecolor='white', alpha=0.7))

    ax.set_xlabel('MDS Dimension 1', fontsize=12)
    ax.set_ylabel('MDS Dimension 2', fontsize=12)
    ax.set_title(f'A. Before Procrustes\n{subject} {roi} (6 runs overlaid)', fontsize=14)
    ax.grid(alpha=0.3)
    ax.axhline(0, color='black', linewidth=0.5, alpha=0.5)
    ax.axvline(0, color='black', linewidth=0.5, alpha=0.5)

    # Panel B: After Procrustes
    ax = axes[1]

    for run in range(n_runs):
        patterns = amplitudes_procrustes[run]
        rdm = compute_rdm(patterns)

        mds = MDS(n_components=2, dissimilarity='precomputed', random_state=42)
        embedding = mds.fit_transform(rdm)

        for i in range(n_colors):
            ax.scatter(embedding[i, 0], embedding[i, 1],
                      c=[COLOR_RGB[i]], s=150, alpha=0.4,
                      edgecolors='black', linewidths=0.5)

    # Labels
    rdm_mean = np.mean([compute_rdm(amplitudes_procrustes[r]) for r in range(n_runs)], axis=0)
    mds = MDS(n_components=2, dissimilarity='precomputed', random_state=42)
    embedding_mean = mds.fit_transform(rdm_mean)

    for i in range(n_colors):
        ax.text(embedding_mean[i, 0], embedding_mean[i, 1], COLOR_NAMES[i],
               fontsize=10, ha='center', va='center',
               bbox=dict(boxstyle='round', facecolor='white', alpha=0.7))

    ax.set_xlabel('MDS Dimension 1', fontsize=12)
    ax.set_ylabel('MDS Dimension 2', fontsize=12)
    ax.set_title(f'B. After Procrustes\n{subject} {roi} (6 runs overlaid)', fontsize=14)
    ax.grid(alpha=0.3)
    ax.axhline(0, color='black', linewidth=0.5, alpha=0.5)
    ax.axvline(0, color='black', linewidth=0.5, alpha=0.5)

    plt.tight_layout()

    output_file = output_dir / f'color_space_embedding_sub-{subject}_{roi}.png'
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"✓ Saved: {output_file}")

    plt.close()


def plot_voxel_tuning_curves(amplitudes_raw, amplitudes_procrustes, output_dir, subject, roi):
    """
    Figure 4: Example Voxel Tuning Curves

    2×4 panel: 8 example voxels
    Each panel: Color responses before/after Procrustes
    """
    n_runs, n_colors, n_voxels = amplitudes_raw.shape

    # Select 8 example voxels (evenly spaced by peak color)
    amp_mean = amplitudes_raw.mean(axis=0)  # (8, n_voxels)
    peak_colors = np.argmax(amp_mean, axis=0)

    # Compute color selectivity: max - mean(others)
    selectivity = np.zeros(n_voxels)
    for v in range(n_voxels):
        peak_c = peak_colors[v]
        peak_response = amp_mean[peak_c, v]
        other_responses = np.delete(amp_mean[:, v], peak_c)
        selectivity[v] = peak_response - other_responses.mean()

    example_voxels = []
    for c in range(n_colors):
        voxels_c = np.where(peak_colors == c)[0]
        if len(voxels_c) > 0:
            # Pick voxel with highest selectivity
            selectivities_c = selectivity[voxels_c]
            best_voxel = voxels_c[np.argmax(selectivities_c)]
            example_voxels.append(best_voxel)

    if len(example_voxels) < 8:
        print(f"⚠️  Only {len(example_voxels)} color-selective voxels found (out of 8 colors)")
        print(f"     Color distribution: {[np.sum(peak_colors == c) for c in range(n_colors)]}")
        # Fill with voxels with highest selectivity
        remaining = 8 - len(example_voxels)
        remaining_voxels = np.setdiff1d(np.arange(n_voxels), example_voxels)
        top_selective = remaining_voxels[np.argsort(selectivity[remaining_voxels])[-remaining:]]
        example_voxels.extend(top_selective)

    fig, axes = plt.subplots(2, 4, figsize=(16, 8))
    axes = axes.flatten()

    for idx, voxel_idx in enumerate(example_voxels[:8]):
        ax = axes[idx]

        # Before Procrustes (average across runs)
        tuning_before = amplitudes_raw[:, :, voxel_idx].mean(axis=0)  # (8,)
        tuning_before_std = amplitudes_raw[:, :, voxel_idx].std(axis=0)

        # After Procrustes
        tuning_after = amplitudes_procrustes[:, :, voxel_idx].mean(axis=0)
        tuning_after_std = amplitudes_procrustes[:, :, voxel_idx].std(axis=0)

        # Plot
        x = np.arange(n_colors)
        ax.errorbar(x - 0.1, tuning_before, yerr=tuning_before_std,
                   fmt='o-', color='coral', alpha=0.7, label='Before',
                   capsize=3, capthick=1)
        ax.errorbar(x + 0.1, tuning_after, yerr=tuning_after_std,
                   fmt='s-', color='skyblue', alpha=0.7, label='After',
                   capsize=3, capthick=1)

        # Color background
        for i in range(n_colors):
            ax.axvspan(i - 0.4, i + 0.4, facecolor=COLOR_RGB[i], alpha=0.1)

        ax.set_xticks(x)
        ax.set_xticklabels(COLOR_NAMES, rotation=45, ha='right', fontsize=8)
        ax.set_ylabel('Amplitude', fontsize=10)
        ax.set_title(f'Voxel {voxel_idx} (peak: {COLOR_NAMES[peak_colors[voxel_idx]]})',
                    fontsize=10)
        ax.grid(axis='y', alpha=0.3)

        if idx == 0:
            ax.legend(loc='upper left', fontsize=8)

    fig.suptitle(f'Voxel Tuning Curves: {subject} {roi}', fontsize=16, y=0.98)
    plt.tight_layout()

    output_file = output_dir / f'voxel_tuning_curves_sub-{subject}_{roi}.png'
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"✓ Saved: {output_file}")

    plt.close()


def main():
    parser = argparse.ArgumentParser(description='Visualize color geometry and voxel patterns')
    parser.add_argument('--subject', type=str, required=True, help='Subject ID (e.g., 01)')
    parser.add_argument('--roi', type=str, required=True, help='ROI name (e.g., V1)')
    parser.add_argument('--output-dir', type=str, default=None,
                       help='Output directory (default: results/baseline/visualizations)')

    args = parser.parse_args()

    # Output directory
    if args.output_dir is None:
        output_dir = BASE_DIR / 'visualizations'
    else:
        output_dir = Path(args.output_dir)

    output_dir.mkdir(parents=True, exist_ok=True)

    print("="*80)
    print(f"Color Geometry Visualization: sub-{args.subject} {args.roi}")
    print("="*80)

    # Load data
    print(f"\nLoading data...")
    amplitudes_raw, amplitudes_procrustes = load_subject_data(args.subject, args.roi)
    n_runs, n_colors, n_voxels = amplitudes_raw.shape
    print(f"✓ Loaded: {n_runs} runs, {n_colors} colors, {n_voxels} voxels")

    # Generate visualizations
    print(f"\nGenerating visualizations...")

    print("  Figure 1: Voxel-Color Amplitude Heatmaps...")
    plot_voxel_color_heatmaps(amplitudes_raw, amplitudes_procrustes, output_dir,
                              args.subject, args.roi)

    print("  Figure 2: RDM Matrices per run...")
    plot_rdm_matrices(amplitudes_raw, amplitudes_procrustes, output_dir,
                     args.subject, args.roi)

    print("  Figure 3: Color Space Embedding (MDS)...")
    plot_color_space_embedding(amplitudes_raw, amplitudes_procrustes, output_dir,
                               args.subject, args.roi)

    print("  Figure 4: Voxel Tuning Curves...")
    plot_voxel_tuning_curves(amplitudes_raw, amplitudes_procrustes, output_dir,
                            args.subject, args.roi)

    print("")
    print("="*80)
    print("✅ Visualization complete!")
    print("")
    print(f"Generated files (in {output_dir}):")
    print(f"  - voxel_color_heatmap_sub-{args.subject}_{args.roi}.png")
    print(f"  - rdm_matrices_per_run_sub-{args.subject}_{args.roi}.png")
    print(f"  - color_space_embedding_sub-{args.subject}_{args.roi}.png")
    print(f"  - voxel_tuning_curves_sub-{args.subject}_{args.roi}.png")
    print("="*80)


if __name__ == "__main__":
    main()
