#!/usr/bin/env python3
"""
Apply Procrustes Alignment to Baseline Results

Applies orthogonal Procrustes transformation (after center + scale normalization)
to all subject-ROI pairs from baseline pipeline.

Usage:
    python apply_procrustes_baseline.py

Inputs:
    results/baseline/sub-{ID}/{ROI}/amplitudes_raw.npy

Outputs:
    results/baseline/sub-{ID}/{ROI}/amplitudes_procrustes.npy
    results/baseline/sub-{ID}/{ROI}/procrustes_disparities.npy

Author: Generated by Claude Code
Date: 2026-01-30
"""

import numpy as np
from pathlib import Path
import sys

# Add utils to path
sys.path.insert(0, str(Path(__file__).parent / 'utils'))
from procrustes_normalized import procrustes_normalized

# Configuration
SUBJECTS = [f"{i:02d}" for i in range(1, 11)]
ROIS = ['V1', 'V2', 'V3', 'hV4']
BASE_DIR = Path(__file__).parent / "results" / "baseline"

def apply_procrustes_single(subject, roi, verbose=True):
    """
    Apply Procrustes to single subject-ROI pair

    Returns:
        bool: True if successful, False if skipped/failed
    """
    result_dir = BASE_DIR / f"sub-{subject}" / roi

    # Check if input exists
    raw_path = result_dir / "amplitudes_raw.npy"
    if not raw_path.exists():
        if verbose:
            print(f"⚠️  Skip: sub-{subject}/{roi} (amplitudes_raw.npy missing)")
        return False

    # Check if already processed
    procrustes_path = result_dir / "amplitudes_procrustes.npy"
    if procrustes_path.exists():
        if verbose:
            print(f"⚠️  Skip: sub-{subject}/{roi} (already processed)")
        return False

    try:
        # Load raw amplitudes
        amplitudes_raw = np.load(raw_path)

        # Check shape
        if amplitudes_raw.ndim != 3:
            raise ValueError(f"Invalid shape: {amplitudes_raw.shape} (expected 3D)")

        n_runs, n_colors, n_voxels = amplitudes_raw.shape

        if n_runs != 6:
            raise ValueError(f"Expected 6 runs, got {n_runs}")
        if n_colors != 8:
            raise ValueError(f"Expected 8 colors, got {n_colors}")

        # Apply Procrustes
        amplitudes_aligned, disparities = procrustes_normalized(
            amplitudes_raw,
            reference='mean'
        )

        # Save aligned amplitudes
        np.save(procrustes_path, amplitudes_aligned)

        # Save disparities
        disparity_path = result_dir / "procrustes_disparities.npy"
        np.save(disparity_path, disparities)

        # Summary statistics
        mean_disparity = np.mean(disparities)

        if verbose:
            print(f"✓ sub-{subject}/{roi}: n_voxels={n_voxels}, "
                  f"disparity={mean_disparity:.1f} (range: {np.min(disparities):.1f}-{np.max(disparities):.1f})")

        return True

    except Exception as e:
        print(f"❌ sub-{subject}/{roi}: {e}")
        return False


def main():
    """Apply Procrustes to all subject-ROI pairs"""

    print("="*80)
    print("Procrustes Alignment - Baseline Pipeline")
    print("="*80)
    print(f"Subjects: {len(SUBJECTS)} (sub-01 ~ sub-10)")
    print(f"ROIs: {len(ROIS)} (V1, V2, V3, hV4)")
    print(f"Total: {len(SUBJECTS) * len(ROIS)} pairs")
    print("")

    # Statistics
    n_success = 0
    n_skip = 0
    n_fail = 0

    disparities_all = []

    # Process all subject-ROI pairs
    for subject in SUBJECTS:
        for roi in ROIS:
            success = apply_procrustes_single(subject, roi, verbose=True)

            if success:
                n_success += 1

                # Collect disparity for statistics
                disparity_path = BASE_DIR / f"sub-{subject}" / roi / "procrustes_disparities.npy"
                if disparity_path.exists():
                    disp = np.load(disparity_path)
                    disparities_all.append(np.mean(disp))
            else:
                # Check if it was a skip or fail
                raw_path = BASE_DIR / f"sub-{subject}" / roi / "amplitudes_raw.npy"
                if not raw_path.exists():
                    n_skip += 1
                else:
                    n_fail += 1

    print("")
    print("="*80)
    print("Summary")
    print("="*80)
    print(f"✅ Successful: {n_success}/{len(SUBJECTS) * len(ROIS)}")
    print(f"⚠️  Skipped:    {n_skip} (missing input)")
    print(f"❌ Failed:     {n_fail}")

    if disparities_all:
        print("")
        print("Procrustes Disparity Statistics:")
        print(f"  Mean:   {np.mean(disparities_all):.1f}")
        print(f"  Median: {np.median(disparities_all):.1f}")
        print(f"  Std:    {np.std(disparities_all):.1f}")
        print(f"  Range:  [{np.min(disparities_all):.1f}, {np.max(disparities_all):.1f}]")

    print("")
    if n_success == len(SUBJECTS) * len(ROIS):
        print("✅ All subject-ROI pairs processed successfully!")
        print("")
        print("Next steps:")
        print("  1. Download results from server")
        print("  2. Run: python evaluate_baseline_all.py")
        print("  3. Run: python analyze_procrustes_effects.py")
    else:
        print(f"⚠️  Only {n_success}/{len(SUBJECTS) * len(ROIS)} pairs processed")
        print("   Check logs for missing/failed subjects")

    print("="*80)


if __name__ == "__main__":
    main()
