#!/bin/bash
#SBATCH -J diagnostic
#SBATCH -c 4
#SBATCH --mem=64G
#SBATCH -t 10:00:00
#SBATCH -o logs/diagnostic_%j.out
#SBATCH -e logs/diagnostic_%j.err
#SBATCH --nodelist=node2

export PYTHONUNBUFFERED=1
export PYTHONDONTWRITEBYTECODE=1

# Navigate to project directory
cd /scratch/connectome/haba6030/colorBlind

# Load conda environment
source ~/.bashrc
conda activate nilearn

# Run diagnostic analysis
echo "Starting ROI build..."
python -u build_roi_masks.py --subject P01

echo "Fix and Check..."
python -u fix_roi_overlap.py
python -u quick_roi_check.py
python -u data_sanity_check.py

echo "Starting Candid diagnostic analysis..."
python -u python CANDID_fir_reconstruction_universal_hrf.py --roi V2 --use-pca --n-components 20

#python diagnostic_analysis.py
echo "Starting PERSUB diagnostic analysis..."
python -u python PERSUB_fir_reconstruction_universal_hrf.py --subject P01 --roi V2 --use-pca --n-components 20


echo "Diagnostic analysis complete!"